cmd/notary/keys.go
trustmanager/filestore.go
trustmanager/filestore_test.go
trustmanager/x509utils.go

@endophage removed GUN references for the FileStore as you requested.
The FileStore still does operations on directories (which might be sightly counterintuitive), but at least now it's explicit that you're removing a directory, and should pass a param accordingly.
This also bails if you pass a file, instead of a directory.

Removed all references of GUN from filestore

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify.go
cmd/notary/cli_crypto_service.go
cmd/notary/keys.go
cmd/notary/main.go
cmd/notary/tuf.go
notarymysql/start
trustmanager/filestore_test.go
trustmanager/x509filestore.go
trustmanager/x509memstore.go
trustmanager/x509memstore_test.go
trustmanager/x509store.go
trustmanager/x509store_test.go
trustmanager/x509utils.go

As part of bootstrapping a TUF client, validate the downloaded root.json against our cert store. Per conversation with @NathanMcCauley the logic is as follows:
1. Parse root.json
2. Read Key IDs associated with the root role.
3. Read keys (from the root.json) associated with the root role key IDs.
4. Validate keys from root.json against local cert pool.
5. Using only keys that validated against cert pool, validate signatures on the root.json, requiring a threshold of 1.

validate root file against cert store

---

cmd/notary/cli_crypto_service.go
cmd/notary/keys.go
cmd/notary/main.go
trustmanager/filestore.go
trustmanager/filestore_test.go
trustmanager/keyfilestore.go
trustmanager/keyfilestore_test.go
trustmanager/x509filestore.go
trustmanager/x509store.go
trustmanager/x509store_test.go
trustmanager/x509utils.go

@NathanMcCauley @endophage @dmcgowan 
Implementation of a keyfilestore that supports encrypted files. Nathan convinced me that this is the right way of storing encrypted keys.
This will be the basis for the encrypted storage of root keys, and I will add support for bundling soon (for export)

Added a keyfilestore with encrypted PEM support

---

client/client.go
client/client_test.go
client/helpers.go
cmd/notary/tuf.go

Remove "transport", because it's not used.
In the actual notary client, pass in a hard-coded URL for now (same one
previously hardcoded in getRemoteStore). In tests, create a trivial HTTP
server using net/http/httptest, which returns a timestamp.key file.

Change NotaryRepository to honor the baseURL passed in

---

circle.yml

We don't need to build on go 1.3.x, especially if it is missing crypto functionality being used by notary or tuf

Remove use of old version of Docker in circle build

---

cmd/notary-server/README.md

The example configuration given in README.md is missing a comma character and doesn't form valid JSON. 
This PR adds the comma as required.

Fix example configuration file given in README.md

---

cmd/notary-server/main.go

Work around bug in viper configuration.
Viper will always use the default since it matches the whole key match first.
Setting the default to a map keeps the config file as the first matched item.

Fix default log level

---

utils/http.go

The token server returns tokens with the type as "repository" not "repo".
Example token body
```
{
"access": [
{
"type": "repository",
"name": "dmcgowan/busysleep2",
"actions": [
"pull",
"push"
]
}
],
"aud": "notary.docker.io",
"exp": 1436827486,
"iat": 1436827186,
"iss": "auth.docker.io",
"jti": "7n6E3t3-EdKg1D_Cgbg0",
"nbf": 1436827186,
"sub": "dmcgowan"
}
```

Fix access controller resource type

---

notarymysql/Dockerfile
notarymysql/initial.sql
notarymysql/start

This makes it easy for Richard to use to bootstrap our staging and production databases (also for anyone else that wants to run a local db rather than a container)

refactoring database schema out into its own file

---

server/handlers/default.go

ECDSA timestamp keys currently not supported by crypto service, use support ED25519.

Change fallback timestamp algorithtm to supported version

---

client/client.go
client/client_test.go
cmd/notary/tuf.go
cryptoservice/crypto_service.go
cryptoservice/unlocked_crypto_service.go
keystoremanager/keystoremanager.go

This structure encapsulates what used to be "rootKeyStore" "privKeyStore", and the certificate stores. These are being moved out of NotaryRepository, so that operations like listing keys, importing keys, and exporting keys aren't tied to a NotaryRepository structure.
This PR also moves the CryptoService and UnlockedCryptoService to a dedicated cryptoservice package.
Key import/export will be added in a subsequent PR.

KeyStoreManager

---

cmd/notary-signer/main.go
signer/api/api.go
signer/api/api_test.go
signer/api/ed25519_signer.go
signer/api/ed25519_signer_test.go
signer/api/ed25519_signing_service.go
signer/api/ed25519_signing_service_test.go
signer/api/rpc_api.go
signer/api/rpc_api_test.go
signer/api/rsa_signing_service.go
signer/keys/key_db.go
signer/keys/keys.go
signer/signer.go

This causes notary-signer to use gotuf's Key interface instead of
defining its own redundant types.
We can go further with this in the future by removing the redundant
ED25519 implementation. This would be refactored into the cryptoservice
package, and notary-signer would be changed to use that package's
cryptoservice for key creation and signing operations.

Change notary-signer to use gotuf's key types

---

client/client.go
client/client_test.go
keystoremanager/keystoremanager.go

Add convenience methods to KeyStoreManager to add certs to both cert
stores.

Rename certificate stores to trustedCertificateStore and trustedCAStore

---

cmd/notary-server/config.json
docker-compose.yml
notary-server-Dockerfile

Add a service name and ephemeral ports to notary server.
Remove certs as TLS is terminated in the ELB.
Signed-off-by: Richard Scothern <richard.scothern@gmail.com>

Fix the staging deployment.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/endophage/gotuf/data/keys.go
Godeps/_workspace/src/github.com/endophage/gotuf/data/root.go
Godeps/_workspace/src/github.com/endophage/gotuf/data/types.go
Godeps/_workspace/src/github.com/endophage/gotuf/keys/db.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/ed25519.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/interface.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/sign.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/sign_test.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verifiers.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verifiers_test.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify_test.go
Godeps/_workspace/src/github.com/endophage/gotuf/store/dbstore.go
Godeps/_workspace/src/github.com/endophage/gotuf/store/memorystore.go
Godeps/_workspace/src/github.com/endophage/gotuf/tuf.go
client/client_test.go
cryptoservice/crypto_service.go
cryptoservice/unlocked_crypto_service.go
keystoremanager/import_export.go
keystoremanager/keystoremanager.go
server/timestamp/timestamp.go
signer/api/rsa_hardware_crypto_service.go
signer/keys/keys.go
signer/signer.go
signer/signer_trust.go
trustmanager/keyfilestore.go
trustmanager/x509utils.go

@diogomonica @endophage @NathanMcCauley 
Functions should now take data.PublicKey or data.PrivateKey instead of
data.Key.

Updates to notary for gotuf's split of PublicKey and PrivateKey interfaces

---

client/client_test.go
cmd/notary/tuf.go
server/server.go

@diogomonica @NathanMcCauley 
This instantiates a temporary server, publishes some targets to it, and
makes sure we can pull back the correct targets from the server.
Also fixes a few problems with the client unit tests, error reporting in
the client, and logging in the server.

Add a unit test for publish

---

Makefile

It shouldn't depend on .cover, because the makefile doesn't say how to
builld .cover.
It also needs to be included in .PHONY so "make cover" forces coverage
to be run.

Fix cover target in Makefile

---

server/handlers/default.go
server/server.go

Ping endpoint added so clients can get the list of authentication challenges before making an initial request.
The clients could be coded without a ping endpoint but that requires closer integration of the token auth with the client which does not currently exist. This is the fastest approach to get authentication functional.

Add ping endpoint

---

signer/signer_trust.go

These missing functions aren't used, so they're not strictly necessary
at this point. However, it's cleaner to fully implement the interface
than to have functions that don't work with TODO comments.

Implement missing functions in NotarySigner to fully satisfy CryptoService interface

---

client/client.go
cmd/notary/tuf.go
keystoremanager/import_export.go
keystoremanager/keystoremanager.go
pkg/passphrase/passphrase.go
signer/api/rpc_api_test.go
trustmanager/keyfilestore.go

The logic to retrieve passphrase is generic and may be used by directly by clients.

Move passphrase logic to its own package

---

client/client_root_validation_test.go
cryptoservice/crypto_service.go
keystoremanager/import_export.go
keystoremanager/import_export_test.go
keystoremanager/keystoremanager.go
trustmanager/keyfilestore.go
trustmanager/keyfilestore_test.go

Adds a cache to the keystores. The purpose is to prevent the user from entering a passphrase multiple times if there are multiple target keys.
Adds a new test for the cache, and updates existing tests that are affected by the cache.

Key caching

---

cmd/notary/tuf.go

Signed-off-by: Nathan McCauley <nathan.mccauley@docker.com>

fix hash compare on verfy to be bytewise

---

pkg/passphrase/passphrase.go
trustmanager/keyfilestore.go

Also, wrap the passphrase instructions paragraph at 80 columns, and
change the passphrase variable name in addKey to avoid a conflict with
the package name.

Avoid printing "Passphrases do not match" when passphrase is too short

---

cmd/notary/keys.go
cmd/notary/main.go
keystoremanager/import_export.go
keystoremanager/import_export_test.go

Add key import and export commands
This adds four commands:
- notary keys export: export all keys, or keys for a particular GUN (with -g)
- notary keys export-root: export root key by ID
- notary keys import: import a zip file of keys
- notary keys import-root: import a single root key
Change "notary keys" command to "notary key"
This makes the full subcommand names smoother; for example "notary key generate" instead of "notary keys generate".
Add a "notary key list" subcommand to list keys, so "notary key" lists the possible subcommands, instead of needing to use "notary key -h".
@diogomonica

Import export cli

---

trustmanager/x509utils.go

Rather than the global source.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Use the random reader passed as argument to GenerateED25519Key.

---

notarymysql/initial.sql

gorm uses timestamp to represent time.Time, not datetime

---

cmd/notary/cert.go
cmd/notary/keys.go
cmd/notary/main.go
cmd/notary/tuf.go
keystoremanager/import_export.go
keystoremanager/import_export_test.go
trustmanager/keydbstore.go
trustmanager/keyfilestore.go
trustmanager/keystore.go

- Added a new cli cert command
- Changed the keylisting to be a map instead of list
- Fixed removal of normal keys, and force root keys deletion to need -r

Added cli cert command, changed keylisting to be a map

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify_test.go
Godeps/_workspace/src/github.com/endophage/gotuf/store/errors.go
Godeps/_workspace/src/github.com/endophage/gotuf/store/httpstore.go
server/timestamp/timestamp.go

Makes use of an update in gotuf to properly check expirations. Notary will now use the gotuf expiration checking function directly.

Update expiration logic

---

cmd/notary-signer/main.go
signer/keydbstore.go
signer/keydbstore_test.go

The key database is not generally used but only used by the signing service.
Move the implementation to the signer package to be imported by the signer.
ping @endophage

Move key database to signer package

---

cmd/notary-server/main.go
cmd/notary-signer/main.go

For example, trust_service.type becomes
NOTARY_SERVER_TRUST_SERVICE_TYPE.

Accept configuration parameters from environment variables

---

server/server.go
utils/http.go

The current image regex from distribution does not work for `hostname:port` or anything non-lowercase ascii alpha numeric. Rely on the authentication service to restrict users to only pushing valid names.

can't be so restrictive on notary's GUN matching in URLs

---

Makefile
notary-server-Dockerfile
notary-signer-Dockerfile

compile the notary server binary statically in the notary server image so that it can then be copied from the container into a scratch docker image
ping @aaronlehmann then you can use `FROM scratch`

compile the notary server binary statically 

---

.gitignore
Godeps/Godeps.json
Godeps/_workspace/src/code.google.com/p/gosqlite/sqlite3/driver.go
Godeps/_workspace/src/github.com/endophage/gotuf/client/client.go
Godeps/_workspace/src/github.com/endophage/gotuf/client/client_test.go
Godeps/_workspace/src/github.com/endophage/gotuf/data/targets.go
Godeps/_workspace/src/github.com/endophage/gotuf/data/types.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify.go
Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify_test.go
Godeps/_workspace/src/github.com/endophage/gotuf/store/httpstore.go
Godeps/_workspace/src/github.com/endophage/gotuf/testutils/repo.go
Godeps/_workspace/src/github.com/endophage/gotuf/tuf.go
Godeps/_workspace/src/github.com/endophage/gotuf/utils/utils.go
Godeps/_workspace/src/github.com/google/gofuzz/.travis.yml
Godeps/_workspace/src/github.com/google/gofuzz/CONTRIBUTING.md
Godeps/_workspace/src/github.com/google/gofuzz/LICENSE
Godeps/_workspace/src/github.com/google/gofuzz/README.md
Godeps/_workspace/src/github.com/google/gofuzz/doc.go
Godeps/_workspace/src/github.com/google/gofuzz/example_test.go
Godeps/_workspace/src/github.com/google/gofuzz/fuzz.go
Godeps/_workspace/src/github.com/google/gofuzz/fuzz_test.go
client/client.go
server/handlers/default.go
server/handlers/validation.go
server/handlers/validation_test.go

This adds server side validation of root, top level targets, and snapshots during an update (timestamps are not validated because the server will generate them).
It validates:
- that a root rotation is correct if detected.
- that the signatures on all items being updated are correct.
- that the hashes in snapshot are correct for the things being updated and unchanged for the things that aren't being updated.
This also vendors an updated gotuf with some minor improvements: https://github.com/endophage/gotuf/pull/40
In before @NathanMcCauley: working on tests 

server side validation during updates

---

cmd/notary/keys.go
keystoremanager/import_export.go
keystoremanager/import_export_test.go
trustmanager/filestore.go

- Export symlinks by encoding them in the zip file.
- Detect symlinks in a zip file on import and create them on the local
filesystem.
- Add test coverage.

Import and export symlinks in keystore

---

pkg/passphrase/passphrase.go

Let the user know why passphrase wasn’t accepted.
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

Update passphrase error message

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/distribution/registry/client/auth/api_version.go
Godeps/_workspace/src/github.com/docker/distribution/registry/client/auth/authchallenge.go
Godeps/_workspace/src/github.com/docker/distribution/registry/client/auth/authchallenge_test.go
Godeps/_workspace/src/github.com/docker/distribution/registry/client/auth/session.go
Godeps/_workspace/src/github.com/docker/distribution/registry/client/auth/session_test.go
Godeps/_workspace/src/github.com/docker/distribution/registry/client/transport/http_reader.go
Godeps/_workspace/src/github.com/docker/distribution/registry/client/transport/transport.go
cmd/notary/tuf.go

Supersedes https://github.com/docker/notary/pull/162
Adds token auth capabilities to notary cli. For any interactions that require a user to be authenticated (private repos, pushes, etc...) the user will always be asked for username and password (@thaJeztah, no caching of credentials :-).
~~Authentication is enabled with the `--auth` or short form `-a` flags. Valid values are "token" to enable docker style token authentication, or "" to disable authentication. We plan to support HTTP basic auth at some point in the future but it is not an immediate requirement.~~ As @dmcgowan points out below, auth is required or not by the server and there's not point in having a CLI flag, it just confuses things. It has been removed.

Notary cli auth

---

client/changelist/changelist.go
client/changelist/changelist_test.go
client/changelist/file_changelist.go
client/changelist/file_changelist_test.go
client/changelist/interface.go
client/helpers.go

+ Ref https://github.com/docker/notary/issues/144
+ Create ChangeIterator interface
+ Implement ChangeIterator interface for memChangeList
+ Implement ChangeIterator interface for fileChangeList
+ Add iterator test case to changelist_test
+ Add iterator test case to file_changelist_test
+ Change func applyChangelist to use iterator per PR comment
+ Remove redundant defer statement in file_changelist_test.go (PR comment)
+ Change Next error check to simple array bounds check (PR comment)
+ Add negative unit test cases to increase code coverage

Add ChangeIterator interface for Changelists

---

client/client.go
client/client_test.go
cmd/notary/main.go
cmd/notary/tuf.go

The status command will display output in the form:
```
$ notary status com/testing
Unpublished changes for com/testing:
action    scope     type        path
----------------------------------------------------
create    targets   target      README.md
$ notary status com/testing2
No unpublished changes for com/testing2
```
Signed-off-by: Ryan Cox <ryan.a.cox@gmail.com>

Add support for 'notary status' command 

---

notarymysql/migrate.sql
server/storage/database_test.go
server/storage/interface.go
server/storage/models.go

In preparation for gorm-izing the DB itself.
This way we have passing tests we know work against the previous non-gorm storage package before gorm-izing the storage package.

Convert the server DB tests to use GORM with SQLite3 instead of sqlmock

---

circle.yml

The code referes to canonical import paths, so the code needs to be
available there even if CircleCI is building from a forked repository.
Otherwise the tests fail, e.g. https://circleci.com/gh/mtrmac/notary/3 vs. https://circleci.com/gh/mtrmac/notary/4 .

Use canonical import paths instead of forked repo name

---

circle.yml

Thus, we will actually test that the Makefile works.
Doesn’t yet convert test/override because the two already differ and
it’s not immediately obvious to me which one to use.
This should help to avoid future regressions like #213 , (well, apart from not converting the actual test execution ☺).

Use Makefile targets for test/pre to avoid duplication

---

circle.yml
cmd/notary-server/main.go
cmd/notary-signer/main.go
notary-server-Dockerfile
notary-signer-Dockerfile
signer/signer_trust.go
signer/signer_trust_test.go

Fixes #190.
This PR makes notary-server unhealthy if:
~~- the connection to the trust service is dead~~
~~- it takes too long to answer an RPC call~~
~~- the trust signer service is unhealthy~~
~~- the trust key manager service is unhealthy~~
- the DB does not have the right tables
Update: It logs an error if the following are true:
- the connection to the trust service is dead
- it takes too long to answer an RPC call
- the trust signer service is unhealthy
- the trust key manager service is unhealthy
Since the server can operate with the signer down, but someone should get paged.
Note that the DB table query times out after a little while, the GRPC one seemed to hang forever (by which I mean about 10 minutes by wall clock).  It keeps trying to reconnect, but meanwhile the outstanding …

Healthchecks for notary-server

---

docs/Dockerfile

@SvenDowideit created a patch to Hugo 15 which supports GitHub relative source links
This removes the scripts we were using to preprocess
Updates the Dockefile to use the new patch

Retooling for Hugo 15 patch

---

cmd/notary-server/main.go
cmd/notary-signer/main.go
cmd/notary/main.go
cmd/notary/tuf.go
version/version.go

Well, this still has a singleton instance.  But not the `viper` package's private singleton instance.This way we can start injecting different configurations into helper functions in tests.

Do not use the viper singleton instance everywhere

---

cmd/notary-signer/main.go
cmd/notary/tuf.go
server/server.go
signer/signer_trust.go
signer/signer_trust_test.go
trustmanager/x509filestore.go
trustmanager/x509filestore_test.go
utils/tls_config.go
utils/tls_config_test.go

So that mutual authentication can be supported between notary-server and notary-signer as well as notary and notary-server.

Factor out TLS configuration code for server and TLS

---

server/server.go

Fixes #230.  Some healthcheck package refactoring may be necessary to avoid the wrapper function around health.StatusHandler.
@vikstrous Would this be ok as the endpoint to check if this is the notary server?  It either 200's or 503's.

Add the health handler to the main server

---

client/client.go
client/client_root_validation_test.go
client/client_test.go
cmd/notary/keys.go
cmd/notary/tuf.go
keystoremanager/import_export.go
keystoremanager/import_export_test.go
keystoremanager/keystoremanager.go
signer/keydbstore.go
trustmanager/keyfilestore.go
trustmanager/keyfilestore_test.go
trustmanager/keystore.go

This leaves handling the `root_keys` and `tuf_keys` subdirectories to the `KeyFileStore` rather than having `KeyStoreManager` (which is going to be removed in the future) have a non-root `KeyFileStore` and a root `KeyFileStore`.
We cannot do away with the `root_keys` and `tuf_keys` subdirectory completely because we still have to be able to read repos in that format.  And if we see a `tuf_keys` subdirectory, we can't be sure if it's the old-style file structure, or if someone added a GUN that started with `tuf_keys`.
This also makes the following changes:
1. `KeyStore` now has `ImportKey` and `ExportKey` functions, so each `KeyStore` can decide for itself whether and how to import/export keys.
2. After discussion with @endophage, importing a root key now requires you to decrypt the key, …

Unify root nonroot keystore

---

Makefile
circle.yml
coverpkg.sh

As per #213, #217, and #222, attempting to make the CircleCI config use make targets.  To that end I factored the `cover` a bit so that the testing/coverage part is the same across `make cover` and `make ci`.
We were also running short tests before on CI, which doesn't hit all code paths (for instance in the client.go tests we don't test with RSA keys)
cc @mtrmac (although apologies, in #213 you suggested using godep in all targets or none - I haven't done that here since not using godep lets us test various versions for development, but not using godep seems to fail in circleci - maybe we should just do a godep restore in circleci?)
This seems to work (see https://codecov.io/github/cyli/notary?branch=codecov), but the code coverage numbers as displayed in codecov.io are different than …

Use make targets in circleci, more complete coverage

---

cryptoservice/certificate.go
cryptoservice/crypto_service.go
cryptoservice/crypto_service_test.go
signer/keydbstore.go
trustmanager/x509utils.go
tuf/data/keys.go
tuf/signed/ed25519.go
tuf/signed/verifiers_test.go

This builds on top of #243 to make all private key implementers also implement crypto.Signer. This moves towards making additional signing options much more modular as current the cryptoservice has to have at least some knowledge of the various signing mechanisms. This implementation allows us to push specifics of signing implementations into small cohesive types.
TODO:
* ~~New___PrivateKey functions need to return an error in case parsing of the private key fails.~~
* ~~#247 should be merged before this then we should update cryptoservice.Sign to call the private key signing functions.~~

Private keys implement crypto.Signer

---

cmd/notary/keys.go
keystoremanager/import_export.go
keystoremanager/import_export_test.go

PR #242 has started requiring a passphrase for the imported key, and
recomputes the key ID, making the command-line argument redundant.  So,
remove it from the command line and from the KeyStoreManager API.
Also updates the comment for KeyStoreManager.ImportRootKey, and changes
(notary key import-root) to refuse unexpected arguments instead of
silently ignoring them.

Remove key ID from (notary key import-root)

---

Dockerfile.server
Dockerfile.signer
Makefile
README.md

Also and add a target to the makefile to check the go version so we can avoid errors like in #244.

Update README to reflect go 1.5.1 requirement

---

cmd/notary/keys.go

-c was recently taken over by --configFile; using it for --change-passphrase as well results in
panic: shorthand redefinition
So, move --change-passphrase to -p.

Fix (notary key export-root)

---

tuf/signed/verifiers_test.go
utils/tls_config_test.go

This curve is not available on Fedora and RHEL systems, so removing the
reference allows tests to pass there.  Vast majority of the
curve-specific work is done in the golang crypto/elliptic package, so
this does not weaken the tests noticeably.

Don't use elliptic.P224()

---

Makefile

OLD:
```
jessie at debian in ~/notary on fix-makefile
$ ./bin/notary version
notary
Version:    '1.0-rc1'
Git commit: 'ab66379'
```
WITH PATCH:
```
jessie at debian in ~/notary on fix-makefile
$ ./bin/notary version
notary
Version:    1.0-rc1
Git commit: ab66379
```

Fix version in makefile

---

client/client.go
client/client_test.go
tuf/store/httpstore_test.go

Currently, when listing, publishing, or getting a particular target, if the remote server errors, the client attempts to load it from a local cache.  However, if there is no local cache, it just returns Metadata Not Found for listing and getting.  Have it report the remote the original remote error instead of Metadata Not Found locally.
Fixes #277.

Fixes client to report problems contacting the remote server.

---

client/client_test.go
client/client_test_pkcs11.go
client/repo.go
client/repo_pkcs11.go
cmd/notary/cert.go
keystoremanager/keystoremanager.go
keystoremanager/keystoremanager_test.go

The root generation code is handled by CryptoService now.
Fixes #274.

Remove KeyStoreManager's dependency on a KeyStore.

---

cmd/notary/integration_test.go
cmd/notary/keys.go

import-root/export-root have been renamed to import/export.
Fixes #283.
I'm wondering if we should just remove import/export of a single key because backup/restore also does that.

Rename command line options from export/import key to backup/restore.

---

cmd/notary/tuf.go

headers were still printing when no targets were found

---

Makefile

Since if they are generic test helpers that should be exported,
they should probably go into their own package.  If they are used
during testing, they should end in _test.

Make vet target now also checks for filenames with _test_ in the middle.

---

certs/certmanager.go
certs/certmanager_test.go
client/client.go
client/client_root_validation_test.go
client/client_test.go
client/repo.go
client/repo_pkcs11.go
cmd/notary/cert.go

Since it no longer depends upon KeyStore, nor does it manipulate keys
in any way.

Renamed keystoremanager to certs, and KeyStoreManager to Manager.

---

server/handlers/validation.go
server/handlers/validation_test.go
tuf/store/httpstore.go
tuf/store/httpstore_test.go

If the client sends a root.json with an invalid timestamp key ID,
possibly because they are pushing an existing repo to a new server,
then the server should reject the update.
Fixes #297

Server check that the root.json's timestamp key ID is valid.

---

Dockerfile.server
Dockerfile.signer
cmd/notary-server/config.json
cmd/notary-server/main.go
cmd/notary-server/main_test.go
cmd/notary-signer/config.json
cmd/notary-signer/main.go
cmd/notary-signer/main_test.go
docker-compose.yml
fixtures/server-config-local.json
fixtures/server-config.json
fixtures/signer-config-local.json
fixtures/signer-config.json
utils/configuration.go
utils/configuration_test.go
utils/tls_config.go
utils/tls_config_test.go

This factors out some config file parsing utilities common to server and signer.  This makes the config files look a lot more similar, but it also adds a few changes:
1.  Both server/signer server TLS have the following parameters now:
- `tls_cert_file` (signer was previously `cert_file`)
- `tls_key_file` (signer was previously `key_file`)
2. Both the server/signer have the following http parameters now:
- `http_addr` (server was previously `addr`)
3. Both the server/signer have the following logging parameters now:
- `debug` as a string value (signer was previously an int)
4. Both server/signer now support Bugsnag reporting (previously the signer did not)
5. The default alias for the signer DB store are also available as config file parameters under "storage" now.  The password remains …

Make the server/signer configurations more similar

---

cmd/notary-server/main.go
cmd/notary-server/main_test.go

Previously, if it wasn't a remote service, the config parser was
still setting the key algorithm to be whatever was configured.
Now, if we are using a local trust service, the algorithm is always
ED25519.
Also broke the trust parsing into its own function for testing.
Fixes #298.

Fixed bug parsing trust service info in notary server.

---

cmd/notary-signer/main.go

It's no need to keep the `err` after asserting it should be `nil`, and
we can merge these two logs into one I suppose.

Tiny refactor

---

Makefile
circle.yml

~~This needs someone with admin access to docker org needs to grant access to codecov and enable this repo in codecov.io.~~ Done
Also, [codecov.io](https://codecov.io), like [coveralls](https://coveralls.io), does line coverage rather than statement coverage, but this seems better than no coverage check.

Re-enable pushing coverage reports to codecov.io

---

server/handlers/default.go
server/server.go

Rather than further fragmenting the code as we add support for server side snapshotting, I'd rather unify the handler that serves requests to retrieve TUF metadata. Conceptually I think it will make some of the logic a little clearer.

unify the timestamp handler with the handler for getting other tuf metadata

---

migrations/README.md
migrations/server/mysql/0001_initial.down.sql
migrations/server/mysql/0001_initial.up.sql
migrations/signer/mysql/0001_initial.down.sql
migrations/signer/mysql/0001_initial.up.sql

Adds a super simple migrations solution to keep a handle on database changes. The initial files for the server and signer are current for the master branch.
cc @vikstrous @cyli @NathanMcCauley 

initial database migration state

---

cmd/notary-server/main.go
migrations/server/mysql/0002_role_on_keys.down.sql
migrations/server/mysql/0002_role_on_keys.up.sql
notarymysql/migrate.sql
server/handlers/validation.go
server/handlers/validation_test.go
server/storage/database.go
server/storage/database_test.go
server/storage/errors.go
server/storage/interface.go
server/storage/memory.go
server/storage/memory_test.go
server/storage/models.go
server/timestamp/timestamp.go
server/timestamp/timestamp_test.go

Unfortunately the database is still called "timestamp_keys" and I'm not sure how to fix that cleanly. Everything else has been generalized though so that one piece of ugly legacy hangover is highly contained to the database migration files, and the `Key.TableName` method.

Generalize server keys

---

client/client_root_validation_test.go
client/client_test.go

Also, eliminate the timestamp JSON constant and just generate a new
one for the tests.
The client test now also uses KeyFileStore and certs.Manager to
verify the keys and certs on disk, rather than directly manipulating
the files themselves.  This way, if the exact implementation of
KeyFileStore or certs.Manager changes, this test won't fail so long
as KeyFileStore and certs.Manager are self-consistent.

Refactor the client TestInitRepo test into reusable helper functions.

---

cmd/notary-signer/main.go
signer/keydbstore/keydbstore.go
signer/keydbstore/keydbstore_test.go

Rather than create an SQL DB, then create a gorm BD using the SQL
DB.  Also split the Create/Get test into two tests.
This also fixes #336

KeyDBStore refactor so that it just directly takes the DB arguments.

---

cmd/notary-server/main.go
cmd/notary-signer/main.go
utils/configuration.go
utils/configuration_test.go

None of these `filename`, `ext` or `configPath` should be in `main`,
they are all just for creating a instance of Viper and then nothing.
Do it in a separate function will make the function `main` more readable.

Add a function to parse viper

---

client/client.go
client/client_test.go
cryptoservice/crypto_service.go
cryptoservice/crypto_service_test.go

When the user insists on an invalid passphrase (or aborts the operation), `CryptoService.GetPrivateKey` will try the correct root location first, correctly failing, and then try to look for the root key in the $gun subdirectory, and so will return the last error, a confusing
> open $path: no such file or directory
So, recognize the passphrase-related errors and fail with them directly.
Also remove misleading passphrase-related error handling in `NotaryRepository.Initialize`:
1. It is on a path where those errors can never happen
2. The specific error handling would silently ignore the error, which can’t be right anyway.

Fix error handling on invalid root passphrase

---

certs/certmanager_test.go
client/client.go
cmd/notary/prettyprint_test.go
cryptoservice/certificate.go
cryptoservice/certificate_test.go
trustmanager/x509utils.go
trustmanager/x509utils_test.go
trustmanager/yubikey/yubikeystore.go
tuf/signed/sign_test.go
utils/tls_config_test.go

This is a small subset of #267 , but mergeable and useful stand-alone:
Add an explicit `time.Time` parameter to `cryptoservice.GenerateCertificate` and `trustmanager.NewCertificate`.  This will allow writing tests of certificate expiry by generating appropriate certificates.
Then, tighten `TestNewCertificate` to use equality comparisons and fix a revealed bug in `trustmanager.NewCertificate`, which was claiming to expire certificates in 10 years but did not account for leap days in the calculation.

Cert expiration

---

server/handlers/default_test.go
tuf/store/httpstore_test.go

```
server/handlers/default_test.go:353: GetCurrent passes Lock by value: handlers.failStore contains github.com/docker/notary/server/storage.MemStorage contains sync.Mutex
tuf/store/httpstore_test.go:208: github.com/docker/notary/tuf/validation.ErrBadRoot composite literal uses unkeyed fields
```

Fix (make vet)

---

client/client_test.go

#351 was merged, which changed an expected error type of a test in #335.

Fix semantic merge conflict.

---

docker-compose.yml

In case someone is deploying in production directly by doing `docker-compose up` from notary, we might as well make sure they don't lose data by accident.

Adding a volume to MySQL container to ensure data persistence

---

client/client.go
client/client_test.go
cmd/notary/keys.go
cmd/notary/keys_test.go
cmd/notary/main.go
cmd/notary/tuf.go

This is based on #335, and adds the command line utility to rotate a single key (and optionally tell the remote server to manage it).
This involves a fairly large refactor of `cmd/notary/keys.go` in order to remove some of the global mutable state, so that the functions are testable.

Client rotate snapshot key to server

---

client/changelist/change.go
client/changelist/change_test.go
client/client.go
client/helpers.go
client/helpers_test.go
tuf/data/keys.go
tuf/data/roles.go
tuf/data/roles_test.go
tuf/data/snapshot.go
tuf/data/snapshot_test.go
tuf/tuf.go
tuf/tuf_test.go
tuf/utils/utils.go
tuf/utils/utils_test.go

I debated on whether `UpdateDelegations` should create the delegations file in the case it doesn't exist, but that's not necessarily possible in the general TUF case due to what keys the parent owner wants present on the delegation. Creation of this file will happen at a higher level (i.e. in NotaryRepository). When adding that functionality, we will likely want to update `repo.InitTargets` to take a role name.

Delegation primitives up to changelist level

---

tuf/data/roles.go
tuf/data/roles_test.go

Addresses https://github.com/docker/notary/issues/375, by adding two more checks.
The regex checks against  whitelisted characters: alphabetical, numerical, underscore, and slashes.
`filepath.Clean` removes extra slashes and dots from the URL, but does not handle whitespaces and other characters .

add extra validation checks to isDelegation

---

client/changelist/change_test.go
client/client.go
client/client_test.go
server/handlers/validation_test.go
tuf/client/client_test.go
tuf/data/roles.go
tuf/data/roles_test.go
tuf/tuf_test.go
tuf/utils/utils_test.go

the empty string should be used in delegation Paths to indicate a role can sign everything

---

client/client.go
client/client_test.go
client/helpers.go
client/helpers_test.go
server/handlers/validation_test.go
tuf/client/client.go
tuf/tuf.go
tuf/tuf_test.go

This makes the following logic changes:
- publish now iterates over all targets marked dirty and publishes only those that are dirty (this means canonical targets will not always get pushed)
- if changes are applied to a role that doesn't exist, publish will fallback on its parent role and so forth until it finds a role that exists.  the changes will be applied to that role.
- delegations metadata is not always created when a delegation is created
- role checks now check keyDB rather than the metadata, because the metadata may not exist
- if the role exists, but metadata doesn't, it is now created before being modified (as opposed to just failing before)

Publishing delegation changes, and targets to delegations

---

passphrase/passphrase.go
passphrase/passphrase_test.go

Not a ton of coverage, but just wanted to make sure it would work when we created delegation keys, signed stuff with them, etc.

Add basic tests for passphrase retriever to make sure it handles delegations

---

client/client_root_validation_test.go
client/client_test.go
server/handlers/default.go
tuf/client/client.go
tuf/store/filestore.go
tuf/store/filestore_test.go

A couple more negative test cases from https://github.com/docker/notary/issues/363
Semantic conflict with #385

More client writing/publishing negative tests

---

client/client.go
client/client_test.go
tuf/store/errors.go

returns `ErrRepoNotInitialized` to guarantee proper repo initialization (calling `repo.Initialize()`) and also change the format of `ErrMetaNotFound` to simplify string matching in testing

fixes errors in notary for testing

---

tuf/utils/role_sort.go

According to https://golang.org/src/strings/compare.go?s=491:520#L3
It's suggested to use the built-in string comparison operators.
And also, seems like this function does not exist in some arch
such as arm64. So we better not use it.
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

Do not use strings.Compare

---

client/client.go
client/client_test.go
cmd/notary/prettyprint.go
cmd/notary/prettyprint_test.go
tuf/client/client.go
tuf/client/client_test.go

The output looks like:
```
NAME                                DIGEST                                SIZE (BYTES)    ROLE    
----------------------------------------------------------------------------------------------------
v1     454fd6f9e5a71c34902a673f66cc73be5890785b55014afb0eee6cbbe784cca9   243            targets  
```
I'm not sure I like the role in `Target` being ignored when adding - should there just be two objects?  An adding `Target` and a listing `TargetWithRole`?
(It's being ignored because otherwise it would be a much larger change to how `AddTargets` works, and also adding a target to multiple roles would be more tedious - I don't feel super strongly though, so if anyone thinks it should go the other way I'll be happy to make the change)

When listing targets, the role the target belongs to is also listed

---

client/helpers.go
server/handlers/validation.go
tuf/client/client.go
tuf/data/roles.go
tuf/data/roles_test.go
tuf/tuf.go

Replaces `path/filepath` operations with just `path` operations when dealing with TUF roles because `path/filepath` is OS-specific (for Windows it will produce a different path, for example).  `path` functions will adhere to our TUF role format of `X/Y/Z`
Inspired by discussion in this PR https://github.com/docker/docker/pull/18887#discussion-diff-48414110L40

use path instead of filepath to express TUF roles

---

trustmanager/yubikey/pkcs11_linux.go

On some x86_64 Linux distributions the libaries are installed in /usr/lib64, e.g. Fedora. Without that notary does not work with the Yubikey on these Linux distributions. Adding that path to the search list fixes that issue and makes workrounds like copying/installing the libraries in /usr/lib or /usr/local/lib unnecessary.
Signed-off-by: Udo Seidel <udoseidel@gmx.de>

added /usr/lib64 to search paths

---

Dockerfile.signer

4443 is default used by Server and 4444 is for Signer.

Fix the exposed port in Dockerfile

---

tuf/data/roles.go

Moves regex compilation to outer variable as an optimization, since `IsDelegation` is called in quite a few places.  From @aaronlehmann's comment in https://github.com/docker/notary/pull/394#issuecomment-169396464

Move regex compilation to outside var for optimization

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/stretchr/testify/require/doc.go
Godeps/_workspace/src/github.com/stretchr/testify/require/forward_requirements.go
Godeps/_workspace/src/github.com/stretchr/testify/require/forward_requirements_test.go
Godeps/_workspace/src/github.com/stretchr/testify/require/requirements.go
Godeps/_workspace/src/github.com/stretchr/testify/require/requirements_test.go
client/backwards_compatibility_test.go
client/client.go
client/client_root_validation_test.go
client/client_test.go
client/helpers.go
server/handlers/default_test.go
server/handlers/validation.go
server/handlers/validation_test.go
server/snapshot/snapshot.go
server/snapshot/snapshot_test.go
server/timestamp/timestamp.go
server/timestamp/timestamp_test.go
tuf/client/client_test.go
tuf/data/snapshot.go
tuf/data/timestamp.go
tuf/testutils/repo.go
tuf/tuf.go
tuf/tuf_test.go

Related to #366.
It's safe to change serialization because all deserialization is done AFTER checking hashes and sizes.

use canonical json for all marshalling of TUF data

---

cmd/notary-server/main.go
cmd/notary-signer/main.go

This defaults notary server and signer to use JSON as its output format for logging so that we can integrate it with Heka/Kibana.
It's possible to revert to the logfmt output by passing the CLI flag `-logf=logfmt` (default is `-logf=json`)
cc @diogomonica 

using JSON logging format

---

tuf/client/client.go
tuf/store/errors.go
tuf/store/filestore.go
tuf/store/memorystore.go

Improve the error message for `ErrMetaNotFound` by always specifying the missing resource in the error message string.  This is the first part of https://github.com/docker/docker/issues/15463 (the other errors are from the docker repo)

improve message for ErrMetaNotFound

---

client/client.go
client/client_test.go

- it is easier to understand what's going on in the online functions of NotaryRepository
- we can test NotaryRepository.Update independently (although it'd be nice to have some way
of ensuring that the actual public functions of NotaryRepository like ListTargets,
GetTargetByName, and Publish actually calls Update.
- distinct error if the remote repo doesn't exist.
This also stops wrapping signed.ErrExpired in client.ErrExpired, and just passes
signed.ErrExpired on directly.
This is one step towards #345.

Combine bootstrapClient and tuf/client's Client.Update into a single Update function 

---

client/client_test.go
server/handlers/default.go
server/handlers/validation.go
server/handlers/validation_test.go
tuf/client/client.go
tuf/data/roles.go
tuf/data/roles_test.go
tuf/data/snapshot.go
tuf/data/snapshot_test.go
tuf/data/timestamp.go
tuf/data/types.go
tuf/tuf.go
tuf/tuf_test.go

It adds a lot of complexity without adding much value. If somebody wants custom role names they can implement it at the display level.
Closes #372 

removing the ability to configure role names. 

---

signer/client/signer_trust.go

When I deploy Notary, the health check of Notary-Server began to warn me:
```
level=error msg="Trust not fully operational: Trust is not healthy"
```  
I think the error message is not enough to find the problem, I spent much time to figured out that was because I forget to start the MySQL for Notary-Signer.
With this PR, if the same thing happened, the error message will be quite useful:
```
level=error msg="Trust not fully operational: Trust is not healthy: map[DB operational:Cannot access table: private_keys]"
```

Verbose health check information

---

client/backwards_compatibility_test.go
client/client.go
client/client_root_validation_test.go
client/client_test.go
client/helpers.go
server/handlers/default_test.go
server/handlers/validation.go
server/handlers/validation_test.go
server/snapshot/snapshot.go
server/snapshot/snapshot_test.go
server/timestamp/timestamp.go
server/timestamp/timestamp_test.go
tuf/client/client_test.go
tuf/data/snapshot.go
tuf/data/timestamp.go
tuf/testutils/repo.go
tuf/tuf.go
tuf/tuf_test.go

This reverts commit f417c834c49d32e6aa9bdbbc1ba5c544c0f760b2.

Revert "switching out to consistently use canonical json for all marshalling of TUF data

---

cmd/notary/keys.go
cmd/notary/tuf.go

Write permissions are required to access the *.key endpoints as they may transparently result in key creation.

when doing getTransport readOnly needs to be false 

---

cryptoservice/crypto_service.go
server/handlers/default.go
tuf/signed/ed25519.go

When pushing an image to Distribution server with Notary enabled at the
first time, client will try to get the root.json and it will fail since
there is nothing in Notary yet.
This patch enhances the error message by adding the error detail.
- "404 GET notary-distribution:5678/busybox:root"
And also update some comments

Log: improve error logging

---

CONTRIBUTING.md

Per today’s phone call, the mailing list is not currently used (and is closed to external contributors). So, drop the link.

Drop mailing list link

---

client/client.go
client/client_test.go
client/helpers.go
tuf/store/offlinestore.go
tuf/store/offlinestore_test.go

Necessary precursor to making root rotations workable. Currently we always download the root.json, regardless of whether we have it in cache. This changes that logic to only download if we don't have one in cache. A newer root may then be downloaded later, as part of a repo update, if a problem is detected per the TUF update rules.

fixing bootstrapClient to prefer cached root

---

Makefile
client/repo_pkcs11.go
cmd/notary/integration_nonpkcs11_test.go
cmd/notary/integration_pkcs11_test.go
cmd/notary/integration_test.go

Also, fix a test with exporting/importing all keys - because a key
that is imported into the yubikey is also backed up on disk, when exporting
all keys, it also gets exported.
@diogomonica was correct and setting up the yubikey and such should have just happened in the init.  because we added other tests (e.g. keys_test.go), the tests for the package cmd/notary break now because those tests don't call setup.

Fix bug where the yubikey store was not prioritized over the filestore in a client repo.

---

client/client.go
client/client_root_validation_test.go
client/client_test.go
tuf/data/root.go
tuf/data/root_test.go
tuf/data/serializer.go

Adds additional tests to ensure that keys aren't unnecessarily created on error,
and that only the required keys to sign are used.
Probably the better way to do this would be to refactor the code some to inject a remoteStore into NotaryRepository, and compare the metadata (which we should probably do anyway).
Then again, this does ensure that we aren't re-signing or pulling out private keys unnecessarily.

Ensure that we do not unnecessarily re-sign/serialize a root.json file on publish

---

client/client.go
client/client_update_test.go
tuf/store/httpstore.go
tuf/store/httpstore_test.go

So that it's slightly friendlier.

Translate ErrMetaNotFound when updating, so long as it's on root, to ErrRepositoryNotExist

---

server/errors/errors.go
server/handlers/default.go
server/handlers/default_test.go

Introduces `ErrOldVersion` to distinguish between errors for invalid versions of metadata and errors for during a DB rollback (`ErrUpdating` was propagated both for errors previously from the `atomicUpdateHandler`).  Closes https://github.com/docker/notary/issues/423

Pass original invalid version storage error details into standardized err

---

notarymysql/initial.sql

Fixing the missing comma that is currently breaking migrations.

Fixing initial.sql syntax

---

trustmanager/x509utils.go

GetLeafCerts and GetIntermediaCerts are similiar and a consistent
implementation will be more friendly to those people who wants to read
the code.

 Keep a consistent coding style

---

certs/certs.go
client/helpers_test.go
server/handlers/default_test.go
server/handlers/validation_test.go
server/integration_test.go
tuf/client/client_test.go
tuf/testutils/repo.go

This involves making it use ECDSA keys since we can't generate ED25519 certs.
This is useful when using `EmptyRepo()` to generate metadata to be served when testing.

Change testutils.EmptyRepo() to use a cert as the root.json root key.

---

certs/certs_test.go
client/client.go
client/client_test.go
cmd/notary/cert.go
cmd/notary/integration_test.go
cmd/notary/keys.go
cmd/notary/main.go
const.go
tuf/store/filestore.go
tuf/store/filestore_test.go
tuf/store/httpstore.go
tuf/store/httpstore_test.go
tuf/store/interfaces.go
tuf/store/memorystore.go
tuf/store/memorystore_test.go
tuf/store/offlinestore.go
tuf/store/offlinestore_test.go

Delete local client repo TUF cache, certs, and keys via the client library.  Closes #449
Also updates `notary cert remove gun` to remove TUF data for that gun.  Closes #462 

client library and cli deletion functionality

---

client/client.go
client/client_test.go
client/helpers.go
client/helpers_test.go
cmd/notary/delegations.go
cmd/notary/delegations_test.go
cmd/notary/integration_test.go
cmd/notary/main.go
cmd/notary/prettyprint.go
cmd/notary/prettyprint_test.go
const.go
cryptoservice/crypto_service.go
trustmanager/x509utils.go
tuf/data/roles.go
tuf/data/roles_test.go

Adds a `notary delegation` command to the cli.  There are three commands:
- `add`: adds a delegation using a given gun, X509 cert(s) with public key, role (ex: "targets/delegation"), and optional comma-separated `--paths`. Currently we only validate the expiry date on the certificate since there are no restrictions on the signature, but it could be backed by the TUF root key or existing PKI in the future. This command creates a TUF change offline, which will need to be published to take effect.
- `remove`: removes delegation info using a gun and role with either key IDs (standard arguments) or comma-separated `--paths`.  The command can also just remove all information for the specified role using a `--force` flag (this requires confirmation).  Creates a TUF change offline (update or …

delegation command for notary-cli

---

cmd/notary/tuf.go
cmd/notary/tuf_test.go
tuf/store/httpstore.go
tuf/store/httpstore_test.go

This only solves for the second error in #468.
~~TODO: need to dig up what specific errors I should be matching when checking the http response error. It probably shouldn't be generic.~~
According to net/http docs, non-2XX responses don't result in an err, which is exclusively reserved for protocol problems or client configuration directives. Added a check for non-2XX StatusCodes and also setting to offline on those.

Offline operation when server not reachable

---

client/client.go
const.go

It seems that `make vet` sometimes disagrees locally vs on CircleCI.  This
just fixes my local `make vet` complaints.
Sometimes my local `make vet` seems to let me get away without commenting, too, so I'm not sure where the disparity is.

Add some comments about the notary constants, and other lint fixes.

---

Makefile
client/client_update_test.go
tuf/store/filestore.go
tuf/store/filestore_test.go
tuf/store/httpstore.go
tuf/store/interfaces.go
tuf/store/memorystore.go
tuf/store/offlinestore.go
tuf/store/store_test.go
tuf/testutils/repo.go
tuf/testutils/swizzler.go
tuf/testutils/swizzler_test.go

Trying to keep this PR size relatively manageable in size (sorry, it's pretty big :().  This includes a utility and some tests for updating a repo when the repo itself has been corrupted.
Tests to update a repo when the server has corrupted metadata are forthcoming in another PR.
(note this PR also removes coverage calculation for the testutils package, which is a library we use only for testing)
Closes #451
Partially addresses #361

Update tests while messing up metadata

---

cmd/notary/tuf.go
cmd/notary/tuf_test.go

I had an incorrect understanding of the response codes that would be returned from `/v2/`. A 401 is considered valid and will result in authentication being done later.
Tests have been added to ensure tokenAuth succeeds when the server returns a 401

tokenAuth should also 'succeed' if we get a 401

---

client/client_update_test.go
tuf/client/client.go

I re-worked the first couple of tests in `client_update_tests` to cover more cases and moved them to the bottom of the file.
I also changed client so that:
1.  we don't get an unexpected end of JSON error when the server errors while downloading a timestamp
2.  we just use the cached timestamp now when the server 404's on getting a timestamp (previously, we used the cached timestamp when we got any other error than 404 - not sure we should default to cached if we do get a 404, but the behavior should probably be consistent for non-200 status codes)
3.  warn users that we are using a stale timestamp file and hence may have a stale view of the repo, if we use the cached timestamp
Partially addresses #361.

Add tests for when the server 404's or 50X's when updating

---

client/client.go
client/client_test.go
tuf/data/roles.go
tuf/keys/db.go
tuf/tuf.go
tuf/tuf_test.go

client library function `ListRoles` to get all current state for a repository's roles including keys and signatures.  Adds a new `RoleWithSignatures` object to express role state that wraps each `Role` with its signatures in a `RoleWithSignatures` object.
Also fixes some typos.
Partially addresses #446.

get all current role information for a repo

---

cmd/notary/integration_test.go
cmd/notary/main.go

Currently the default logging level is error - it'd be nice to have configurable logging levels for notary, and only default to a higher level such as `fatal` for a less noisy CLI.
This is motivated by when I was testing remote snapshot rotation via the CLI, and any online command after the `key rotate` command brought about an Info log for a signature mismatch for Snapshot, and an associated Error log.  This is particularly noisy in this instance because these logs occur before we download a new root and retry the TUF update, ultimately running the command successfully to completion:
```
$ notary key rotate snap3 -t snapshot -r true
$ notary publish snap3
Pushing changes to snap3
Enter passphrase for root key with ID b96f107:
$ notary list snap3
INFO[0000] failed ECDSA signature …
```

allow for configurable log level, change default for CLI

---

Makefile
circle.yml

Since we have a single builder, and they're slow, we don't want this to be a bottleneck.  If we can figure out how to have multiple VMs, one for each yubikey in the builder, then we can probably start running full tests again.

Don't run all the tests with yubikey

---

cmd/notary/delegations_test.go
const.go
trustmanager/x509utils.go

If the cert we're adding to the delegation has a RSA key and it's too short (< 2048), we'll reject before adding the delegation.  Without this check, the server will reject when we try to publish with the short key.  Closes #504.

Add check for RSA key len before adding delegation

---

tuf/client/client.go
tuf/signed/verifiers.go

Reduces log levels for signature verification and update() failures to debug, to avoid confusing situations when calling notary library.  The two main situations this helps are when rotating the snapshot key to server (snapshot validation fails before updating the root meta) and when publishing with delegations (signatures won't validate for keys you do not possess).  Closes #507 

move verifier and update logs down to debug level

---

tuf/store/httpstore.go
tuf/store/httpstore_test.go

Closes #288 
We've made other changes that mean we can better message a 401 on the client. This just provides a clearer error message.

return a better error message if the HTTP status code was 401

---

cmd/notary/main.go
cmd/notary/tuf.go

The other CLI commands about tuf are all begin with cmdTufXXX
which I think `verify` should be the same too.

Tiny refactor: to keep code style consistent

---

client/client.go
client/client_update_test.go
const.go
tuf/client/client.go
tuf/client/client_test.go
tuf/store/filestore.go
tuf/store/filestore_test.go
tuf/store/httpstore.go
tuf/store/httpstore_test.go
tuf/store/memorystore.go
tuf/store/memorystore_test.go
tuf/testutils/swizzler.go
tuf/testutils/swizzler_test.go

store/filestore.go's `GetMeta` now considers the `size` argument and will only return up to `size` bytes.  If `size` is -1, we get "all" data for the resource but stop at 100MB under the hood -- this is consistent across the memory, file, and remote stores.  I also refactored `MaxTimestampSize` to const.go for convenience.
This follows up on discussion from https://github.com/docker/notary/pull/494/files#r50593036

ensure filestore GetMeta only returns up to size bytes.  Add max size constant

---

docs/notary-mysql.md
fixtures/server-config.json
fixtures/signer-config.json
notarymysql/Dockerfile
notarymysql/initial-notaryserver.sql
notarymysql/initial-notarysigner.sql
notarymysql/migrate-notaryserver.sql
notarymysql/start

For security, server should not be able to access the `private_key` table
and we can go further more, say, use seperate databases for the server
and signer.
This patch set will do:
- [PATCH 1/4] creates two users corresponding to the different databases.
- [PATCH 2/4] Check whether the database `notary` exist or not and warn people to manually migrate those tables if it exist.
- [PATCH 3/4] make database `notaryserver` and `notarysigner` only create the tables they need.
- [PATCH 4/4] add the recommendation to guide people deploying a more secure MySQL for notary.
Closes #330 
[skip ci]

Use seperate databases for notary server and signer

---

client/client_update_test.go
tuf/client/client.go
tuf/client/client_test.go
tuf/testutils/swizzler.go
tuf/testutils/swizzler_test.go

Adds tests for if the server has invalid checksums, or the metadata is otherwise invalid.
This fixes an issue where, if the server has an invalid timestamp file but one that is unmarshallable to a `data.Signed` object, the update just fails.  It should instead try to fall back on the cached timestamp.  This is not true for any other role (which behave correctly).
There are also a bugs with downloading a new root that has the wrong version when the old root is expired, or downloading a new root during the bootstrap phase that doesn't have enough signatures.  I have not fixed these because I think they require a bigger refactor of `certs.ValidateRoot`, and we should maybe unify the root validations for both bootstrap and regular download.
I've skipped these cases for now.

Update when server metadata is corrupt

---

cmd/notary/integration_test.go
cmd/notary/main.go
cmd/notary/tuf.go
trustmanager/x509utils.go

Adds `--roles` flags to `notary add`/`notary remove`/`notary list` to allow for adding to specific delegations.  The `--roles` flag takes a list of roles.
I used this for testing end-to-end delegation publishing with notary, and there's an integration test that does a publish to `targets/releases` after removing the targets key and copying over the delegation private key to `private/tuf_keys`.  This private key needs either the name format of `canonicalID_releases` or a role in the PEM headers.
Closes #511

Roles for targets via notary CLI

---

client/client.go
client/client_test.go
client/helpers.go
client/helpers_test.go
cmd/notary/delegations.go
cmd/notary/integration_test.go
tuf/tuf.go
tuf/tuf_test.go

Since we display the canonical key ID when asking a delegation user to passphrases and also need to store the key under its canonical key ID when saving to `tuf_files`, it makes sense to only show the canonical ID to the user on notary CLI.
Before this change, we used the TUF key IDs on notary CLI commands, but still required the canonical key ID in the filename and would show the user the canoncial key ID if they needed to enter a passphrase when signing with that key.
This does require us to do more work to translate between key ID types, but this is only done for `delegation list` (to translate TUF key IDs to canonical IDs to show to the user) or a `publish` after a `delegation remove` (to translate user-supplied canonical IDs to TUF key IDs to apply the changelist logic).
This is …

use only canonical IDs for display on delegation CLI commands,

---

docs/cli.md
docs/index.md
docs/notary-mysql.md
docs/notary-server-config.md
docs/notary-server.md
docs/notary-signer-config.md
docs/notary-signer.md
docs/overview.md

For the 1.10 release we are moving to product-name taxonomy to help users find documentation about a product. Registry and Notary are moving under a menu Marketing calls Component Projects. This PR makes this menu:
Note: The rest of the menu may look a bit foobared --- don't freak. I have multiple PRs in play across several repos and when they all close the currently exposed codes will go away.

Notary for 1.10 in docs.docker.com

---

cmd/notary/tuf.go

Make the error log message different from the following
`subtle.ConstantTimeCompare()` in the same function.

Comments: rework some comments

---

client/client.go
client/client_test.go
client/client_update_test.go
server/server.go
tuf/client/client.go
tuf/client/client_test.go
tuf/store/interfaces.go
tuf/store/memorystore.go
tuf/testutils/corrupt_memorystore.go
tuf/utils/utils.go

The client will use the checksum in downloading whenever a checksum is available. This means it will never use one for timestamp and will only use one for downloading root if a snapshot was successfully downloaded first, however it will always use one for downloading the snapshot and all targets (incl. delegations) files.
Also deleted dead code related to loading and downloading targets while I was in the store code. It has never seen use in Notary.

Consistent Download

---

cmd/notary-signer/main.go

The signer will print out the user name and password of the database
which could cause security problem.
The server side is OK.

Stop logging out critical info of database

---

docs/notary-server.md
server/server.go
server/server_test.go

Request from the ops team that prometheus metrics for server are found at /metrics. I guess they use this as a standard endpoint for this info.

update metrics endpoint

---

client/client.go
client/client_update_test.go
client/helpers.go
server/integration_test.go
tuf/client/client_test.go
tuf/store/filestore.go
tuf/store/filestore_test.go
tuf/store/httpstore.go
tuf/store/httpstore_test.go
tuf/store/interfaces.go
tuf/store/memorystore.go
tuf/store/memorystore_test.go
tuf/store/store_test.go
tuf/testutils/corrupt_memorystore.go
tuf/testutils/swizzler.go

Notary does not download actual targets, this removes the last bits of dead code related to that functionality.

removing last vestiges of target download code

---

cmd/notary/delegations.go
cmd/notary/integration_test.go
cmd/notary/prettyprint.go
cmd/notary/prettyprint_test.go

This improves notary CLI to properly display `""` in the console (before it was just blank) and also describes it as `<all paths>`.  This also adds a `--all-paths` flag that will add `""` when used with`delegation add`, and clear all paths on `delegation remove`.  Removing the individual `""` path will only remove that path.
Closes #505.

Ensure empty string path is properly handled, add --all-paths flag

---

cmd/notary/integration_test.go
cmd/notary/keys.go
cmd/notary/keys_test.go

Allows notary CLI to change passphrases for non-root keys, including delegation keys.
There might be some weird behavior with the passphrase retriever on targets/snapshot key if you only change the passphrase for one individually -- #541 would fix this.
Partially addresses #483

add non-root passwd functionality

---

README.md

Just because it bugged me we didn't have the codecov badge and it took 30 seconds to add.

adding codecov badge to readme

---

server/handlers/validation.go
server/handlers/validation_test.go
tuf/client/client.go
tuf/data/roles.go
tuf/signed/verify.go
tuf/signed/verify_test.go
tuf/testutils/swizzler_test.go
tuf/tuf.go

The start of removing KeyDB.  This introduces a `RoleWithKeys` object, which `Verify` uses to verify signatures, instead of a `KeyDB`.
Part of #556

Remove keyDB from signed.Verify

---

cmd/notary/integration_nonpkcs11_test.go
cmd/notary/integration_test.go
cmd/notary/keys.go
cmd/notary/keys_test.go
const.go
cryptoservice/import_export.go
cryptoservice/import_export_test.go
trustmanager/keyfilestore.go
trustmanager/keyfilestore_test.go
trustmanager/x509utils.go

Allows for importing and exporting non-root keys via notary CLI.  This also works for importing delegation keys:
`notary key import <file> --role <ROLE> --gun <GUN>`
The default role is root, so that the behavior of `notary key import <file>` remains unchanged.
export is the same but now also can export non-root keys by ID:
`notary key export <keyID> <file>`
I also made "private", "tuf_keys", and "root_keys" constants in `const.go`
Partially addresses #483 (`passwd` can be a separate PR, along with changes to passphrase retriever)

Non-root key import and export CLI

---

Makefile
certs/certs_test.go
circle.yml
client/changelist/change.go
client/client.go
tuf/README.md
tuf/encrypted/encrypted.go
tuf/tuf_test.go

Fixes current typos and adds `misspell` as a target to the Makefile and as a step in circle ci

Misspell in Makefile and circleci

---

cmd/notary/integration_test.go

It seems like jenkins got into a weird state and didn't actually test this code with yubikeys until now. Without this PR, this test will fail when using a yubikey because it cannot export keys, nor can it import non-root keys.  `TestClientKeyImportExportRootOnly` still tests that importing a root key on a yubikey functions as expected.
@cyli and I investigated the jenkins build configuration, and we've fixed it to ensure it pulls the latest commit off master.

Update integration test to exclude yubikeys from importing/exporting non-root keys

---

tuf/client/client.go
tuf/tuf.go

I noticed a stray and unused `pathHex` that we should remove, since we no longer support path hash prefixes

remove path hash prefix from TargetsDelegations

---

client/client_update_test.go
tuf/client/client.go
tuf/testutils/swizzler.go
tuf/testutils/swizzler_test.go

This completes a lot of the per-metadata-type tests listed in #361

Per metadata type mutation tests

---

Makefile
circle.yml
tuf/data/keys.go

The Makefile check is just annoying so I removed it. We should just add a "requirements" section on the main README.
There has been a change to how encoding/json treats embedded structs. It's loosely described here: https://golang.org/doc/go1.6#reflect The TL;DR is that json now only traverses embedded structs where the struct is exported in its own right (so its name must start with an upper-case letter). 
N.B. Embedded structs themselves do not appear in serialized JSON, they are (conceptually) replaced by their encapsulated fields. Therefore this change does not have compatibility implications and is valid for Go 1.6 and prior versions. 

updates and bugfixes for go 1.6

---

tuf/client/client.go

I originally also added a check to prevent overwriting of targets objects in tuf.Repo.SetTargets but this broke operation as we current re-use the repo object. Adding the check during download should be sufficient to ensure we never write an incorrect child as a second call to SetTargets with an existing delegation will set a validated object.

check validity of children during download

---

client/client.go
client/client_test.go
client/delegations.go
client/helpers.go
client/helpers_test.go
server/handlers/validation_test.go
tuf/client/client.go
tuf/client/client_test.go
tuf/data/root.go
tuf/data/targets.go
tuf/testutils/repo.go
tuf/tuf.go
tuf/tuf_test.go
tuf/utils/utils.go

Defines a `WalkTargets` that walks the targets and delegations structure in a uniform way, and we can pass closures to perform special visit functions to list targets, get targets by name, and get delegation roles.  Also used for adding/removing targets and delegation roles.
This PR also removes unused code that would also find targets or get target meta by walking the targets structure.
Closes #560

WalkTargets on tuf repo for targets and delegations

---

cmd/notary/delegations.go
cmd/notary/integration_test.go

Changes to print the canonical key IDs when adding a delegation, instead of the public key bytes.

print IDs instead of key itself

---

trustmanager/yubikey/yubikeystore.go

When importing to a yubikeystore, we should reject non-root keys upfront before prompting for passphrases or attempting to read key bytes.

Move yubikey import role check to avoid excessive passphrase prompting

---

client/client.go
const.go
server/server.go
server/timestamp/timestamp.go
server/timestamp/timestamp_test.go
tuf/data/types.go

Two related fixes:
- The server was not setting the longer snapshot expiry time consistent with the client. 
- When generating a timestamp it was also retrieving the snapshot directly from the database and only validating the checksum still matched what was in the timestamp. Due to the addition of consistent downloads, this mean a new snapshot never got generated (when the server was responsible for this). It is necessary for `GetOrCreateTimestamp` to call `GetOrCreateSnapshot` to ensure a new snapshot is generated as and when required

Fix server signed snapshot expiry/regeneration

---

client/client.go
cmd/notary/tuf.go
const.go
server/snapshot/snapshot.go
server/timestamp/timestamp.go
tuf/client/client.go
tuf/client/client_test.go
tuf/data/snapshot.go
tuf/data/timestamp.go
tuf/data/types.go
tuf/data/types_test.go
tuf/testutils/swizzler.go
tuf/tuf.go

Closes #412 
This patch set will generate multiple hashes for each target/meta file:
- [PATCH 1/8] Create constants for sha256 and sha512
- [PATCH 2/8] Add some helper functions
- [PATCH 3/8] Add sha512 when creating target, snapshot and timestamp
- [PATCH 4/8] Add sha512 when updating and also make the change on test
- [PATCH 5/8] Add sha512 check on CLI command
- [PATCH 6/8] Add sha512 check when downloading TUF roles and update the relevant test.
- [PATCH 7/8] Updating the server side
- [PATCH 8/8] Some test for the added functions of this patch set

Add SHA-512

---

tuf/tuf.go

I noticed while testing that we aren't being consistent with which format key IDs are messaged on `ErrNoKeys`.  This PR ensures we only message canonical IDs, which is already the case in [`sign.go`](https://github.com/docker/notary/blob/4aa9239aafa4e421134daab980f0c32d45d0ed85/tuf/signed/sign.go#L49)

Message canonical key ids on error

---

docs/advanced_usage.md

Updating the notary docs to document default snapshot key behavior in Docker 1.11 since https://github.com/docker/docker/pull/20890 is merged

Include note about docker1.11 default snapshot key behavior

---

client/client_test.go
cmd/notary-server/config.go
cmd/notary-server/main.go
cmd/notary-server/main_test.go
cmd/notary/integration_test.go
cmd/notary/keys.go
cmd/notary/main_test.go
server/handlers/default.go
server/handlers/default_test.go
server/handlers/roles.go
server/handlers/roles_test.go
server/handlers/validation.go
server/integration_test.go
server/server.go
server/server_test.go
server/snapshot/snapshot.go
server/snapshot/snapshot_test.go
server/storage/database.go
server/storage/database_test.go
server/storage/interface.go
server/storage/memory.go
server/storage/memory_test.go
server/timestamp/timestamp.go
server/timestamp/timestamp_test.go
utils/http.go
utils/http_test.go

This includes the `Cache-Control` header, the `Last-Modified` header, and the `ETag` header (just using sha256 for now).
Fixes #597

Return cache control headers when returning metadata from server

---

client/backwards_compatibility_test.go
client/client.go
client/client_test.go
cmd/notary/integration_test.go
cmd/notary/keys.go
cmd/notary/keys_test.go
cmd/notary/main_test.go
docs/advanced_usage.md

This includes some minor changes from #553.
Fixes #554

Change the CLI to be able to rotate server managed keys

---

tuf/testutils/swizzler_test.go

These calls can fail, and errors would cause false failures later in the
tests.

Don't silently ignore swizzler errors

---

cmd/notary-server/config.go
cmd/notary-server/main.go
cmd/notary-server/main_test.go
const.go
docs/reference/server-config.md

Thanks to @HuKeping for pointing out the issue - when #597 was refactored I removed the defaults and forgot to put them back in.  :|  
This adds them, along with a test to ensure that the default config file can always be parsed without error.
Also, I forgot the doc updates in that PR, so this PR adds them.
Fixes #629

Add defaults to cache-control config parsing

---

client/client_test.go
client/helpers.go
client/helpers_test.go
docs/advanced_usage.md

Given the behavior proposed in https://github.com/docker/docker/pull/21046, the fallback behavior is no longer that necessary -- this PR removes the fallback logic when applying changes on targets entirely.
Docker will be able to determine the roles it will sign for from TUF metadata and private keys in its trust directory, so there is no need to silently fallback on the notary side (I'm especially worried about any potential role confusion)

Remove delegation role fallback when applying targets changes

---

certs/certs_test.go
tuf/signed/sign.go
tuf/signed/sign_test.go
tuf/signed/verify.go
tuf/tuf.go

either because the key is no longer a valid signing key for the role, or the signature is invalid.

remove signatures that are no longer valid during signing

---

tuf/data/types.go

As discovered during hackday, there are double encoding issues if a `json.RawMessage` object is included in a larger JSON object. The official "fix" is to use a `*json.RawMessage`
N.B. we don't use the Custom field anywhere (other than our hackday project which doesn't count) and it's set to `omitempty` so it doesn't appear in any of our json right now, this is an "if we use it in the future" fix

json.RawMessage needs to be a pointer 

---

signer/client/signer_trust.go
signer/client/signer_trust_test.go

This one got away in the flatten keystore PR -- here's a fix and added test to make sure we have coverage.
Also, another reason I'm super excited to have #634 since that test would've caught this :+1: 

Fix Create arg order for signer

---

cmd/notary/integration_test.go
cmd/notary/prettyprint.go
cmd/notary/prettyprint_test.go

Changes the CLI output to print each delegation key and path on its own line, rather than keeping each role to a single line with commas between keys/paths.  Sample below:

Print one key and/or path per line when listing delegations

---

client/backwards_compatibility_test.go
server/handlers/default_test.go
server/handlers/validation.go
server/handlers/validation_test.go
server/integration_test.go
server/snapshot/snapshot.go
server/snapshot/snapshot_test.go
server/timestamp/timestamp.go
server/timestamp/timestamp_test.go
tuf/data/root.go

Sorry for the largish change.
This changes the timestamp and snapshot code generation to just try to sign a generated timestamp and snapshot, and if there aren't enough signatures, to then fail on server-managed keys, which will help us with eliminating the `timestamp_keys` table and allowing us to have multiple signing keys for a gun and role on the signer, which is part of #347.
It also changes timestamp generation to automatically generate a timestamp when an update is sent, which fixes #563.

Server generates snapshot and timestamp immediately

---

misc/docker-integration-test.py

This could be more clever and actually call the vendor script instead of just copying in the whole notary directory, if the SHA we are on is actually available on origin/remote, but I was hoping this would be a way to get the combo script into the docker-in-docker image as well so we can hopefully run a container that contains that script (I haven't figured out how to do that yet)

Add script that "vendors" notary into docker and runs trust integration tests

---

passphrase/passphrase_test.go

Replaces just for the `passphrase` package, part of #628 

Use require instead of assert for passphrase package

---

certs/certs_test.go
trustmanager/filestore_test.go
trustmanager/keyfilestore_test.go
trustmanager/x509filestore_test.go
trustmanager/x509utils_test.go
trustmanager/yubikey/yubikeystore_test.go

Part of #628 for the certs and trustmanager packages, using require instead of assert for testing

Use require for certs and trustmanager

---

signer/api/api_test.go
signer/api/rpc_api_test.go
signer/client/signer_trust_test.go
signer/keydbstore/keydbstore_test.go

Part of #628 to use require for the signer package

Use require instead of assert for signer package

---

cmd/notary-server/main_test.go
cmd/notary-signer/main_test.go
cmd/notary/delegations_test.go
cmd/notary/integration_pkcs11_test.go
cmd/notary/integration_test.go
cmd/notary/keys_test.go
cmd/notary/main_test.go
cmd/notary/prettyprint_test.go

Updates all test assertions to use require in the `cmd` package, part of #628 

Use require instead of assert for cmd

---

cryptoservice/certificate_test.go
cryptoservice/crypto_service_test.go
cryptoservice/import_export_compatibility_test.go
cryptoservice/import_export_test.go

Using require instead of assert for the cryptoservice package, part of #628

Update to use require for cryptoservice package

---

misc/docker-integration-test.py

Since we changed our Godeps structure to the `vendor` directory, this test should also be updated.  Was able to successfully run on my local OSX setup (and all tests passed against master :+1: )

Update vendoring test to use new vendor structure

---

Dockerfile

Not sure what changed, but looks like go vet just comes with the image now and also osxcross breaks unless pinned to a commit.  Copied the OSX cross stuff from docker/docker Dockerfile.
Also bumped the min OSX version to 10.9.

Do not install go vet on the Dockerfile

---

server/server_test.go
server/snapshot/snapshot_test.go
server/storage/database_test.go
server/timestamp/timestamp_test.go
tuf/data/root.go
tuf/data/root_test.go
tuf/data/snapshot.go
tuf/data/snapshot_test.go
tuf/data/timestamp.go
tuf/data/timestamp_test.go

Since it's already embedded in `Targets`.
Will be useful for me for https://github.com/docker/notary/pull/580

Embed SignedCommon in Root, Snapshot, and Timestamp

---

client/backwards_compatibility_test.go
client/client.go
client/client_test.go
client/client_update_test.go
client/delegations.go

Since we don't actually use the TUF client anymore in `NotaryRepository` except during `Update`.
Addresses https://github.com/docker/notary/pull/580#discussion_r55722929.

NotaryRepository.Update now just returns an error, rather than a client and error

---

Makefile
circle.yml

Also, add a check for go >= 1.6

Stop using godep in CI and Makefile since we use vendoring now

---

certs/certs_test.go
tuf/signed/errors.go
tuf/signed/verify.go
tuf/signed/verify_test.go

Adds verification to `Verify` to ensure that the key ID being used to verify signatures is actually correct against its sha256 hash

Key ID verification

---

certs/certs.go
certs/certs_test.go
client/client.go
cryptoservice/crypto_service_test.go
signer/keydbstore/keydbstore.go
trustmanager/keyfilestore.go
trustmanager/keystore.go
trustmanager/yubikey/yubikeystore.go
tuf/signed/sign_test.go

@mtrmac fully implemented root cert (public key) rotations, which in #648 was changed to be a full root rotation as per group code review results.
Some of the cleanups are not as relevant to that feature anymore, but are still really nice, so to try to reduce the size of #648 and make it a little smaller, this PR contains some of the cleanups from that PR.

@mtrmac's cleanups, split from root/cert rotation feature

---

Dockerfile
buildscripts/integrationtest.sh
buildscripts/testclient.sh
development.yml

Ensures that we actually fail when one of the containers in the integration test aborts, since docker-compose may return a 0 exit code when aborting containers.
Relies on https://github.com/docker/notary/pull/674 to be green

Write to file to signal success for make integration

---

misc/dockertest.py

Adds simple build and run tests (which pass when I run the script locally) to the docker versioning integration test.
Also bumps the version for docker 1.10 and updates the command for `notary key rotate`

Build run integration test

---

Makefile
client/client_pkcs11_test.go
client/repo_pkcs11.go
cmd/notary/integration_pkcs11_test.go
cmd/notary/keys.go
cmd/notary/keys_nonpkcs11.go
cmd/notary/keys_pkcs11.go
signer/api/api_test.go
signer/keydbstore/keydbstore.go
trustmanager/yubikey/yubikeystore.go
trustmanager/yubikey/yubikeystore_test.go

`golint ./...` ignores buildtags and somehow didn't pick up some code in the signer.
This calls golint on every go file in the repo and also fixes some linting
issues, which involves renaming two yubikey functions to avoid stuttering.

fix "make lint" to lint every file

---

certs/certs.go
tuf/store/filestore.go

Commit 1(I'm not very sure about this one since the "100MB" here seems more directly):
If we update the maximum value for "infinite" in the future, it is possible
that we forget to update this comments and thus leads misunderstanding.
Commit 2:
Change to a more readable format.

Update some comments

---

README.md
docs/getting_started.md
docs/running_a_service.md

Adding a note to the docs on ensuring that the notary client and server/signer are the same version, also fixed a small typo

Add note about versioning

---

client/client.go
client/client_test.go
cmd/notary/integration_test.go
cmd/notary/main_test.go
cmd/notary/tuf.go
const.go

Introduces a `notary addhash` command.  This command requires a GUN, target name, target byte size, and a sha256 and/or sha512 hash
Closes #649

Add by hash command

---

client/client_update_test.go
cmd/notary/cert.go
cmd/notary/delegations.go
cmd/notary/keys.go
cmd/notary/keys_test.go
cmd/notary/main.go
server/handlers/validation.go
server/handlers/validation_test.go
server/storage/memory.go
server/storage/memory_test.go
trustpinning/certs.go
tuf/data/root.go
tuf/data/root_test.go
tuf/data/snapshot.go
tuf/data/snapshot_test.go
tuf/data/targets.go
tuf/data/targets_test.go
tuf/data/timestamp.go
tuf/data/timestamp_test.go
tuf/signed/verify.go
tuf/testutils/repo.go
tuf/testutils/swizzler.go

This PR:
- adds tests to ensure that server validation or client update during root rotation do not care about old saved root roles, just whatever root role was previously pinned
- tests that root rotation validation checks that the old root role is satisfied, not that a particular key's signature has to be there based on the previous root's signatures
- warns users that they can't just throw away the root key if they rotate the root key
- adds support for root threshold validation - this causes `signed.VerifyRoot` to go away since then it would require the exact same functionality as `signed.VerifySignatures`
Closes #404 probably.

Some root rotation tests and CLI warnings

---

Dockerfile
Godeps/Godeps.json
README.md
circle.yml
server.Dockerfile
signer.Dockerfile

Since we want that security update which could affect HTTPS servers.
Also, the golang:1.6.1-alpine image includes the `no-pic` patch so we should no longer need to pass the `-fno-PIC` flag

Update go in dockerfiles to go 1.6.1

---

cmd/notary-signer/config.go
cmd/notary-signer/main.go
cmd/notary-signer/main_test.go
signer/signer.go

Much prefer the architecture of `func main` of `server` to `signer` , which was changed by @cyli  , it's more simple and clear. 
In my option it's a nicer implementations that we pass the config to each component rather than use the global variable `mainViper`. That makes notary easier to run, to embed, to reuse and to test.
I think maybe we can do the same things on the `signer` side  just like what the `server` does.

Rework the main for notary signer

---

client/client_update_test.go
cmd/notary/tuf.go
server/timestamp/timestamp.go
tuf/client/client.go
tuf/client/client_test.go
tuf/client/errors.go
tuf/data/errors.go
tuf/data/snapshot.go
tuf/data/types.go
tuf/data/types_test.go

Since we already have a ErrMismatchedChecksum in tuf/data/errors.
Also, have the CheckHashes function take a role name so that the
`ErrMismatchedChecksum` error can include the role name.
This is split out from #580 to make it a little smaller.

Remove a redundant ErrChecksumMismatch error in tuf/client

---

README.md

Add explicit instructions for the Go directory structure assumed for `make binaries`
Closes #689 

better docs for make binaries

---

docs/advanced_usage.md

The yubikey information needed to be updated to reflect Docker 1.11

Update docs with yubikey info for docker 1.11

---

trustmanager/x509store_test.go
trustmanager/x509utils.go
trustmanager/yubikey/yubikeystore.go

Fixing a few things I noticed scrolling through the Notary 0.3.0-RC1 diff.

trustmanager: Minor cosmetic source code fixes

---

docs/reference/client-config.md

The relative paths to link to the image are not the same on the published result to that in GitHub due to our use of implied `/index.html` when publishing. 
This means that to do the right transform, we need to use markdown markup for the linking.
This tests right for me in both cases :)

Use markdown to link to image, so the published result shows it

---

cmd/notary/tuf.go

This path enables running notary client list operation on docker.io
private repositories (in official hub).
Signed-off-by: Liron Levin <liron@twistlock.com>

Enable basic authentication for list command

---

cmd/notary-server/config.go
cmd/notary-server/main_test.go
cmd/notary-signer/config.go
cmd/notary-signer/main_test.go
fixtures/server-config.rethink.json
fixtures/signer-config.rethink.json
storage/rethinkdb/rethinkdb.go
utils/configuration.go
utils/configuration_test.go

To connect to RethinkDB over TLS from notary server/signer

Add client key and cert to rethink client tls config

---

cmd/notary-signer/config.go
cmd/notary-signer/main_test.go
signer/keydbstore/rethink_keydbstore.go

Some small cleanup to allow for a configurable notary signer db name in Rethinkdb (this matches the notary server configuration).
Also added a check to `setUpCryptoservices` to actually check against allowed backends and error out if an invalid backend is specified. 
I've also run this against the Rethinkdb integration test with successful results.

Allow for configurable notary signer db name, check allowed backends

---

development.rethink.yml
docker-compose.rethink.yml

This wasn't documented in the official RethinkDB website docs, but we'll need this for mutual TLS on our compose setups:
```
--driver-tls-ca ca_filename                 CA certificate bundle used to verify
client certificates; TLS client
authentication disabled if omitted
```

Add driver-tls-ca flag for rethink

---

cmd/notary/main.go
cmd/notary/main_test.go

Allow for non-delegation names such as `user` to use the `NOTARY_DELEGATION_PASSPHRASE` for usability

Be less strict for password caching for delegation keys 

---

tuf/tuf.go
tuf/tuf_test.go

Save both the previous root role and the current root role on root rotation, however.
Fixes #722 
Fixes #723 
However, Docker < 1.11 will still break as soon as a root rotation is done.

Do not save old root roles until the first root rotation

---

storage/rethinkdb/bootstrap.go

The default timeout for rethinkdb when calling `term.Wait()` is [0 seconds](https://rethinkdb.com/api/javascript/wait/), this bumps it to 60 seconds -- I'd be fine making it shorter as well, but we're checking across all replicas to be ready in this scenario by default.
Also remove extra `.Wait()` after db creation
Tested using the rethinkdb integration test.

Increase timeout for RethinkDB (default is 0), remove extra wait

---

cmd/notary/tuf.go

Check `isTerminal` (same behavior as `/passphrase/passphrase.go`, line 104).
Signed-off-by: Liron Levin <liron@twistlock.com>

Enable using notary client list op with user name/passwords in scripts

---

Godeps/Godeps.json
cmd/notary-server/config.go
cmd/notary-signer/config.go
cmd/notary-signer/main_test.go
const.go
fixtures/server-config.rethink.json
fixtures/signer-config.rethink.json
server/storage/rethinkdb.go
signer/keydbstore/rethink_keydbstore.go
storage/rethinkdb/bootstrap.go
storage/rethinkdb/rethinkdb.go
utils/configuration.go
utils/configuration_test.go
vendor/gopkg.in/dancannon/gorethink.v2/CHANGELOG.md
vendor/gopkg.in/dancannon/gorethink.v2/README.md
vendor/gopkg.in/dancannon/gorethink.v2/cluster.go
vendor/gopkg.in/dancannon/gorethink.v2/connection.go
vendor/gopkg.in/dancannon/gorethink.v2/doc.go
vendor/gopkg.in/dancannon/gorethink.v2/encoding/cache.go
vendor/gopkg.in/dancannon/gorethink.v2/query.go
vendor/gopkg.in/dancannon/gorethink.v2/query_table.go
vendor/gopkg.in/dancannon/gorethink.v2/query_test.go
vendor/gopkg.in/dancannon/gorethink.v2/query_transformation.go
vendor/gopkg.in/dancannon/gorethink.v2/query_write.go
vendor/gopkg.in/dancannon/gorethink.v2/session_test.go

Adds a `server` and `signer` user for rethinkdb databases if we're bootstrapping, in parity with the mysql configuration.  This is a new feature in RethinkDB 2.3, and I also bumped gorethink to account for a bugfix on their end.
All non-bootstrapping invocations of notary-server and notary-signer will directly connect to rethink with its own users (`username`) and passwords (`password`) from the `storage` section of the server and signer configs, respectively.
Currently does not include password changing for admin.
Tested with the rethink integration test.
Closes #730

Add separate users to rethinkDB databases with only read/write permissions

---

development.rethink.yml
development.yml
docker-compose.rethink.yml
docker-compose.yml
server.Dockerfile
signer.Dockerfile
storage/rethinkdb/bootstrap.go

Previously I was running into issues where the server and signer would bootstrap fine, but couldn't connect, so updated the wait options to include "all_replicas_ready", which should be the default already.  But for some reason this seemed to fix the issue for me.  Or it was intermittent, who knows.
But not all the RDB replicas joined the same cluster, when looking at the admin UI - this fixes it for me.

Fix the re-think compose file so that all the rdb nodes join the same cluster

---

tuf/data/types.go
tuf/data/types_test.go

Separating out the multihash comparison from #744 into its own PR, as suggested by @cyli 
This PR adds a multihash comparison utility function for comparing supported hashes.  Note that like `CheckHashes`, unsupported hashes are not compared at all.

Utility function for comparing multihash

---

client/client.go
client/client_test.go

Similar to #744 but more generic -- allows for retrieving all `Target` and `Role` data for a specified target name, in the form of a list of `TargetWithRole` structs

Get all Target and Role data for a given target name

---

development.mysql.yml
docker-compose.yml

Converted the remaining two docker compose files over to the v2 format as suggested in #753 in hopes that the dns server in docker would resolve the hostnames of the containers instead of going off-box for hostname resolution.
Signed-off-by: Andrew Hsu <andrewhsu@acm.org>

convert docker compose files to v2

---

Dockerfile
buildscripts/circle_parallelism.sh
codecov.yml
notary.go

I noticed that we had a slight lint issue and circle wasn't picking it up -- this should fix both the lint error and make sure that errors are reported properly.  This also changes the thresholding on codecov to accept `0.05%` drops in coverage.

fix lint and circle, edit codecov

---

Makefile

I'm sure I'm not the only one who runs these. It's nice to be able to stay on one go version instead of switching for different projects.

allow devel builds of go to pass make version check

---

client/client.go
client/helpers.go
client/helpers_test.go
tuf/testutils/repo.go

Warnings are now output on read and write actions. Should indicate which role will be expiring soon and will need to be re-signed.
Also deleted an unused function in testutils- AddTarget
closes #733

Nearexpirywarnings for re-signing roles on read or write

---

cmd/notary-server/config.go
cmd/notary-server/main.go
cmd/notary-server/main_test.go
const.go
docs/reference/server-config.md
utils/configuration.go
utils/configuration_test.go

Part of #633 
As discussed with the team of notary, it might not make sense to completely reload the configuration yet. 
With this patch set, we can send SIGUSR1/SIGUSR2 to increase/decrease the logging level of notary-server.

Feature: increase/decrease logging level without restarting

---

trustmanager/keyfilestore.go
trustmanager/memorystore.go

Attempted fix of #792. The locks seem to be covered already by the KeyMemoryStore, which is the only place that uses MemoryFileStore.
I think the go vet issue at hand is https://github.com/golang/go/issues/13675#issuecomment-165798626

remove literal copy of sync.Mutex from memory store

---

client/client.go
client/client_test.go
cmd/notary/integration_test.go
cmd/notary/keys_test.go
cmd/notary/tuf.go

This addresses #731 by adding a `--rootkey` flag to `init`.
Example:
```
$ notary init my/collection --rootkey=keys/root.key
```
resulting root.json:
```json
{
"signed": {
"_type": "Root",
"consistent_snapshot": false,
"expires": "2026-06-21T14:20:03.15135742-04:00",
"keys": {
"956fbe52f38738cb5c31b1cbff06842ceda8e429f55164a61349cd233a50813f": {
"keytype": "ecdsa-x509",
"keyval": {
"private": null,
"public": "..."
}
}
// ...
},
"roles": {
"root": {
"keyids": [
"956fbe52f38738cb5c31b1cbff06842ceda8e429f55164a61349cd233a50813f"
],
"threshold": 1
}
// ...
},
"version": 1
},
"signatures": [{
"keyid": "956fbe52f38738cb5c31b1cbff06842ceda8e429f55164a61349cd233a50813f",
"method": "ecdsa",
"sig": "70BvEbnWA1bHoc2IjnIE8XFI1N4I1WQxyd2GDNX/Avfmy89Z5J1w0pL507LpLd1DbV6p6CtqPgCdb5oCMeXt5w=="
}
}]
}
``` …

Support passing in root keys on repo initialization

---

Dockerfile
Makefile
buildscripts/circle_parallelism.sh
server/handlers/validation_test.go

Adds the `ineffassign` target to our Makefile and circle tests, indirectly part of #815 

Include ineffassign in CI, fix ineffassign in code

---

storage/rethinkdb/bootstrap.go

We should call [indexWait](https://rethinkdb.com/api/javascript/index_wait/) in addition to just the table [wait](https://rethinkdb.com/api/javascript/wait/) to ensure that all indexes for the table are ready.
I can add unit-tests to the infrastructure in #824, though the rethink integration test checks out

Wait for indexes in rethink table.wait

---

server/handlers/default.go
server/timestamp/timestamp.go
utils/http.go

Adds info-level logging for 4XX errors and error-level for 5XX in the server.  Also lowers errors on retrieving timestamps to debug-level.
Closes #766

Add info logging for 400s, error for 500s, adjust timestamp error level on GetCurrent

---

client/client.go
cmd/notary/tuf.go

Carry @endophage's suggested cleanups from #801

rootkey init code cleanups

---

cmd/notary/main.go
cmd/notary/main_test.go
tuf/data/roles.go
tuf/data/roles_test.go

Part of the issue noted in #820 

Only use delegation passphrase env var for non-base roles

---

passphrase/passphrase.go
passphrase/passphrase_test.go

Caches each passphrase in the passphrase retriever separately, such that snapshot and targets passphrases are no longer necessarily shared and that we can also cache delegation role passphrases.
Note from previous discussions about how this affects the docker-client integration: the passphrase refactor will affect old repos since we'll ask for targets and snapshots separately, but it will not affect new repos created with Docker 1.11 since the server handles the snapshot key.  Also,  the environment variables for automation remain the same.
Closes #524, carries #541

Refactor passphrase to cache passphrases individually

---

client/client_test.go
client/delegations.go
cmd/notary/integration_test.go
cmd/notary/prettyprint.go
cmd/notary/prettyprint_test.go

Brought up by @HuKeping in https://github.com/docker/notary/issues/852#issuecomment-234137903, I noticed that `translateDelegationsToCanonicalIDs` was mistakenly editing in-memory metadata by replacing TUF key IDs with canonical key IDs, which would cause nested delegations to have issues when building into `data.DelegationRole` structs.
Changed pass-by-reference to pass-by-value and added a test that publishes a nested delegation and ensures that `delegation list` behaves as expected.

Ensure that we do not clobber in-memory key id data on delegation list

---

buildscripts/dbtests.sh
cmd/notary-signer/config.go
server/storage/rethink_realdb_test.go
signer/keydbstore/cachedkeystore.go
signer/keydbstore/cachedkeystore_test.go
signer/keydbstore/keydbstore_test.go
signer/keydbstore/mysql_test.go
signer/keydbstore/rethink_keydbstore.go
signer/keydbstore/rethink_keydbstore_test.go
signer/keydbstore/rethink_realkeydbstore_test.go
signer/keydbstore/sql_keydbstore.go
signer/keydbstore/sql_keydbstore_test.go
signer/keydbstore/sqlite_test.go

This adds specific mysql DB and rethink DB tests for the signer.
It also does the following:
- factors the caching part of the `KeyStore` implementations into a wrapper `KeyStore`
- renames `KeyDBStore` to `SQLKeyDBStore` and add SQL types to the Gorm model (otherwise the schema is not created correctly in MySQL tests)
- changes `SQLKeyDBStore`'s `RemoveKey` to always succeed, even if the key doesn't exist
- store the `RethinkKeyDBStore`'s public and private bytes as `[]byte`, otherwise rethink won't know that it's binary data and will mangle the result - this doesn't matter for the private key bytes, since we encrypt it in such a way that it's base64 encoded, but I changed it anyway in case we want to change encryption method in the future
- fixes `RethinkKeyDBStore`'s key rotation …

Per-DB signer tests

---

buildscripts/dbtests.sh
server/storage/memory_test.go
server/storage/mysql_test.go
server/storage/rethink_realdb_test.go
server/storage/rethinkdb.go
server/storage/sql_models.go
server/storage/sqldb.go
server/storage/sqldb_test.go
server/storage/sqlite_test.go
server/storage/storage_test.go
server/storage/tuf_store_test.go
signer/keydbstore/mysql_test.go

This finishes the refactor in #824 of the server storage tests refactor to take a DB type.
In addition, this fixes:
1.  Deleting a GUN in mysql - previously, we soft-deleted a gun, preventing us from being able to re-use the namespace.  We now hard-delete.
1.  The RethinkDB server health check needs to fail if the session user does not have the correct permissions to access the requisite tables.

More server DB tests

---

trustpinning/certs.go
trustpinning/trustpin.go

Carries #818, and I added a follow-up commit with review feedback.
@dnwake thank you for the original contribution! :)
Closes #817

[Carry #818] Trustpinning debug

---

client/client_update_test.go
tuf/client/client.go

For instance if there aren't enough signatures, or if the metadata is expired

Change download logic to not completely abort in certain delegation failure cases

---

client/client.go
client/client_test.go
client/delegations.go
client/helpers.go
cmd/notary/delegations.go
cmd/notary/delegations_test.go
cmd/notary/integration_test.go
docs/advanced_usage.md
tuf/data/roles.go
tuf/data/roles_test.go
tuf/tuf.go
tuf/tuf_test.go

~~Need to write tests.~~
Closes #696 

command to purge all keys from all delegations below a starting point

---

client/changelist/changelist.go
client/changelist/changelist_test.go
client/changelist/file_changelist.go
client/changelist/interface.go
client/helpers.go
cmd/notary/prettyprint.go
cmd/notary/tuf.go
cmd/notary/tuf_test.go

Needs tests
Partially addresses #596 
Adds `--reset` and `--unstage` flags to `notary status`. `reset` removes all pending changes for the GUN, `unstage` allows specific changes to be removed based on their # as shown in `notary status`

update to allow removing pending changes

---

trustmanager/yubikey/yubikeystore.go

Small update to our debug statement for when we fail to initialize a PKCS11 environment, since this is a common source of confusion.

Change debug phrasing for pkcs11 initialization failure

---

cmd/notary/integration_test.go
cmd/notary/main_test.go
cmd/notary/tuf.go

Wires up `DeleteTrustData` from the client library to a `notary delete` command, which will delete all local TUF metadata by default and additionally the remote metadata if the `--remote` flag is given.
Closes https://github.com/docker/notary/issues/710

notary delete CLI command

---

server/storage/memory.go
server/storage/rethinkdb.go
server/storage/sqldb.go
server/storage/storage_test.go

Fixes #898 
Here I'm just changing this to return the concrete type everywhere.  We could instead just change the type we compare against in https://github.com/docker/notary/blob/master/server/handlers/default.go#L108 to be a pointer instead of a concrete type.

We are returning a pointer to an error rather than an error itself.

---

cmd/notary/delegations.go
cmd/notary/integration_test.go
cmd/notary/tuf.go
cmd/notary/util.go

Closes #885 
Add flag "-p", "--publish" to "notary add", with this flag being set,
notary will attemp to publish after adding the change.

Introduce a flag for auto publishing

---

cmd/notary/tuf.go
passphrase/passphrase.go
passphrase/passphrase_test.go
trustmanager/keystore.go

Fixes some logic in the keystore when counting number of passphrase attempts, especially when short passphrases are provided.
```
🐳 $ bin/notary init testGun
Root key found, using: 4327a8deba2cae19a4b393d2c6cf3a2f349652c84bc41bc1e09ade182d86b19a
Enter passphrase for root key with ID 4327a8d:
Enter passphrase for new targets key with ID 454c204 (testGun):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
Enter passphrase for new targets key with ID 454c204 (testGun):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
...
Enter passphrase for new targets key with ID 454c204 (testGun):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
* …
```

Passphrase fixups

---

cmd/notary/integration_test.go
cmd/notary/tuf.go

Noticed we didn't have auto-publish on `notary witness` while I was working on docs, so I added a quick diff

auto-publish for witness

---

client/client_test.go

`misspell` is catching this (must be a new version)

fix misspelling of timestamp

---

Makefile

@avaid96 noticed that misspell changed up its recursive directory finding-logic (see: https://github.com/client9/misspell#how-do-you-check-an-entire-folder-recursively)

fix misspell find file logic

---

MAINTAINERS

ping @cyli @diogomonica @dmcgowan @endophage  @nathanmccauley @riyazdf :smile: 

Add hukeping to the maintainer list of Notary

---

Dockerfile
Makefile
README.md
server.Dockerfile
signer.Dockerfile

Bumps to go 1.7.0.
We can replace `golang.org/x/net/context` with `context` in a follow-up PR because we'll have to also bump grpc to a version that also uses `context`
Closes #928 

Update go version to 1.7.0

---

Dockerfile
README.md
server.Dockerfile
signer.Dockerfile

Brew doesn't have the 1.7.1 formula yet, so can't update the yubikey tester just yet.

Bump go to version 1.7.1

---

Makefile
buildscripts/cross.sh

Modify the cross-compile script to statically compile the linux binary (which includes libtool).
This hopefully compiles the OS X binary in such a way as to address #826.

Statically compile linux binaries, and try to fix OS X binaries

---

client/client.go
trustpinning/certs.go
trustpinning/certs_test.go
trustpinning/trustpin.go
tuf/builder.go

Check new roots against the trust pinning when performing validation, but do not reject the new root if TOFUs is disabled because we've already trusted a previous root.
Closes #735.

Validate root rotations against trust pinning where appropriate

---

buildscripts/testclient.py
cmd/notary-server/config.go

Integration tests have been failing lately - it seems it's because the server comes up before the signer, and the integration tests start before the server manages to connect to the signer.
This fix should hopefully cause the tests to wait until the server is healthy for sure, so they might take longer to start.
This also changes the definition of notary server health - previously it was healthy but degraded if the signer is down - not it's just unhealthy, because we cannot do any writes.  
An alternate approach is to just have a separate endpoint to see whether it runs in degraded mode, or use a different health package that supports "warning" or degraded mode without necessarily failing the health check entirely.

Try to fix flakey integration tests, also update the definition of notary server health

---

docs/command_reference.md
docs/index.md

This adds a command reference doc, so we can give our users a quicker way to find how to do things like rotate keys with notary CLI.
Inspired by and superseding #904 (thank you again @avaid96 for your work there!)

Add command reference docs

---

cmd/notary/delegations.go
cmd/notary/integration_test.go
tuf/tuf.go

Fixes a couple of bugs with `notary delegation purge`:
- The role that was being purged of keys was not being marked as dirty for publishing
- The auto-publish flag wasn't actually wired up correctly (it was on `delegation list`)
Also reworks the integration test to check that we can successfully purge a key from multiple delegation roles.
Closes #953

Fixes for delegation purge

---

cmd/notary/integration_test.go
cmd/notary/main_test.go
cmd/notary/tuf.go
cmd/notary/tuf_test.go
docs/command_reference.md
docs/getting_started.md

Factors out the `--reset` and `--unstage` flags from `notary status` into a new `notary reset` command.
The `notary status` command now does not have any flags and cannot mutate any state.
- `notary reset <GUN> --all` resets all staged changes for a gun
- `notary reset <GUN> -n 1 -n 2` resets the change items numbered `1` and `2` from `notary status <GUN>`

Introduce `notary reset` command from `notary status` flags

---

client/client.go
client/client_test.go

As noted by @cyli, it seems desirable to wipe out any staged changes for a repo when running `notary delete`.  This PR accomplishes this by deleting the `<trustDir>/tuf/<GUN>` directory, so that we don't have a dangling metadata directory post-deletion.
Currently, notary will persist the changelist subdirectory  `<trustDir>/tuf/<GUN>/changelist` even if a new repo with the same name is initialized, and the changes will attempt to be applied to the new repo (and it can succeed).

Also clear local repo changelist on `notary delete`

---

.gitignore
Makefile
buildscripts/covertest.py
codecov.yml

After some time spent trying to figure out how to reduce CI time in swarmkit, I've noticed a lot of time is spent on compiling the test binaries for each package, as opposed to necessarily just running those tests.  The more packages included in `-coverpkg`, the longer it takes.
Extra time is also taken to compile a binary for packages which have no tests.
So optimize this script to (1) synthesize all the recursive package dependencies as well as the tset dependencies, and (2)  not run `go test` on any packages which don't have any test files.

Speed up coverage calculations

---

cmd/notary/delegations.go
cmd/notary/delegations_test.go

From IRL discussion with @endophage, seems reasonable to have specific error messaging if a cert file doesn't exist.

Update error message for adding delegation if file does not exist

---

client/changelist/file_changelist_test.go
client/client_test.go
cmd/notary-server/main_test.go
cmd/notary-signer/main_test.go
cmd/notary/delegations_test.go
cmd/notary/integration_test.go
cmd/notary/keys_nonpkcs11_test.go
cmd/notary/keys_pkcs11_test.go
cmd/notary/keys_test.go
cmd/notary/main_test.go
storage/filestore.go
storage/filestore_test.go
tuf/tuf_test.go
utils/configuration_test.go

Don't use a temp prefix in any of our `ioutil.TempDir`, etc. calls.
This also creates tempfiles and tempdirs wherever we attempt to directly write to hardcoded location in `/tmp`.
Also change some places that were previously using `path.Join` for file handling to `filepath.Join`.
Addresses a couple of points in #551.

Don't refer to /tmp in any of the tests

---

cmd/notary/keys.go
cmd/notary/tuf.go

Add messages for successful CLI operations, such as `publish` (and `-p`), `delete`, and `key rotate`
Closes #973 

Add CLI prints for successful operations

---

Makefile
buildscripts/circle_parallelism.sh
buildscripts/covertest.py
buildscripts/cross.sh
cmd/notary-server/config.go
cmd/notary-server/main.go
cmd/notary-server/main_test.go
cmd/notary-signer/main.go
cmd/notary/main_test.go
const.go
const_nowindows.go
const_windows.go
docs/reference/server-config.md
docs/reference/signer-config.md
utils/configuration.go
utils/configuration_nowindows.go
utils/configuration_nowindows_test.go
utils/configuration_test.go
utils/configuration_windows.go

Since they don't exist in Windows.  While I was at it, since I had to create a bunch of windows-specific and non-windows-specific files, I moved the signal handling code to `utils` so that it can also be used by the signer (that way we don't have windows/non-windows files for both server and signer).
Technically I think the only change that would have been necessary to make the windows client build is the `const.go` change, and I don't think we care about supporting windows for server/signer, but the server and signer changes are added for completeness (and if we want to run full unit tests in windows).
Unfortunately we don't have any windows CI systems yet.  :|  Although I did add at least cross-compiling to windows to our CI runs.
Addresses part of #551.
Fixes #791.
Note: possibly we …

Do not support SIGUSR1 and SIGUSR2 syscall handling in windows

---

buildscripts/dockertest.py

This PR:
1.  Makes this script work with notary server on docker hub (allow login creds)
1.  Provides more immediate feedback (via subprocess) if there's an error
1.  Bumps the docker 1.12 minor version
1.  Specifies the max notary version that will work with these docker versions

Fix some issues with dockertest and make it work with hub

---

CHANGELOG.md
trustmanager/keystore.go
trustmanager/keystore_test.go

This way a 0.4.1 client can read a repo that a client built from master (with the flattened keystore #872) converts

Be able to read keys even if they are not in the root/non-root subdirs

---

CHANGELOG.md
client/client_update_test.go
client/tufclient.go
storage/httpstore.go
storage/httpstore_test.go

If the client is in offline mode, or encounters some kind of network error when downloading a new timestamp, it should fall back on using the version of the repo in the cache.
Since there a huge number of possible network errors, just wrap any errors received when actually making the HTTP request using the remote store in a `NetworkError`.

Client should fall back on cache if operating offline when updating

---

trustpinning/certs_test.go
tuf/utils/x509.go

This allows non-cert PEM encoded public keys to be loaded as delegation keys

Allow non-cert public keys

---

CHANGELOG.md
CONTRIBUTING.md
README.md

- Added new features in master that are not in 0.4.2 to the changelog for the next release
- Updated the README and CONTRIBUTING doc to reflect the fact that master is our development branch.

Update some of our readme files

---

hooks/build
hooks/push
server.minimal.Dockerfile
signer.minimal.Dockerfile

~~I need to test the builds but samples can be found on docker hub under endophage/notaryauto. These minimal images cut us down from ~160MB to ~5MB~~
~~Reminder to self: reset the docker-compose.yml to master's version before submitting this for review. Been using it to test the new images.~~
Tested and reset docker-compose.yml. These new hooks will be used by anyone setting up an autobuild of this on docker hub/cloud. They produce very minimal images based on busy box. Relative sizes are ~25MB each for server and signer vs a little over 500MB for the existing images built from `server.Dockerfile` and `signer.Dockerfile` (N.B. these are the sizes once unpacked on disk, hub shows much smaller sizes still, unsure if this is a miscalculation or they really compress that well).
p.s. as soon …

custom autobuild script to create minimal build

---

utils/http.go

Since the `docker/distribution` error print does not provide the `Detail` string: https://github.com/docker/distribution/blob/master/registry/api/errcode/errors.go#L116
This should be particularly helpful when we report an `ErrUnknown.WithDetail(err)`

Log detail from distribution errors

---

client/backwards_compatibility_test.go
client/client.go
client/client_test.go
client/client_update_test.go
client/errors.go
client/repo.go
client/repo_pkcs11.go
cmd/notary/delegations.go
cmd/notary/keys.go
cmd/notary/keys_test.go
cmd/notary/tuf.go

Reasonably minimal changes to make cache injectable while not having to move around much code. Also want to keep and add to "helper" constructors (e.g. `NewFileCachedNotaryRepository`) rather than push too much of that code up the call stack.
Also moved a bunch of errors that were in client/client.go into a new client/errors.go to keep things a little cleaner. client/client.go was a bit messy with a bunch of error types. They're still in the same scope (i.e. in the `client` package) so nothing else had to be changed by moving them.

make cache injectable into NotaryRepository

---

Makefile
client/client_test.go
cmd/notary/integration_test.go
cmd/notary/keys_test.go
server/handlers/default_test.go
server/integration_test.go
server/server.go
server/server_test.go
utils/http.go
utils/http_test.go

It seems that golint was updated to prefer `context` being the first parameter when being used in a function:
```
./server/server.go:126:1: context.Context should be the first parameter of a function
./utils/http.go:37:1: context.Context should be the first parameter of a function
```
Also, the `find` in our `Makefile` has been acting up on CircleCI when used for `gocyclo`:
```
find: `gocyclo -over 15 ./client/changelist/change.go': No such file or directory
find: `gocyclo -over 15 ./client/changelist/change_test.go': No such file or directory
find: `gocyclo -over 15 ./client/changelist/changelist.go': No such file or directory
find: `gocyclo -over 15 ./client/changelist/changelist_test.go': No such file or directory
...
```

Lint and gocyclo fixes

---

Godeps/Godeps.json

I removed redundant dependencies that were somehow picked up by godep inside `docker/distribution`'s vendor directory (like `github.com/docker/distribution/vendor/github.com/Sirupsen/logrus`).
Also bumped the major go version to 1.7 and did a `godep save ./...` that resorted and cleaned up the `Godeps.json` file.

Redundant godep vendoring

---

Dockerfile
Makefile
client/client.go

Removes the parent directory creation code from `client.go` because it's already handled by the underlying cache.
Also adds github.com/HewlettPackard/gas to the `make lint` check, though it's a little bit hacky until https://github.com/HewlettPackard/gas/issues/55 and https://github.com/HewlettPackard/gas/issues/50 are resolved.

Add gas check to make lint, fix unnecessary assignment

---

cmd/notary-server/bootstrap.go
cmd/notary-signer/config.go
cmd/notary/keys.go
cryptoservice/certificate.go
signer/keydbstore/cachedcryptoservice_test.go
trustmanager/yubikey/yubikeystore.go
trustmanager/yubikey/yubikeystore_test.go
trustpinning/trustpin.go
tuf/data/keys.go
tuf/signed/verify.go

Removes unnecessary trailing punctuation and newlines from errors, which is now enforced in golint: https://github.com/golang/lint/commit/206c0f020eba0f7fbcfbc467a5eb808037df2ed6
I also removed caps from the beginning of errors in the same files where I found them, though this is not being actively enforced at present.

Do not use trailing punctuation in errors, also no caps where possible

---

trustpinning/certs.go

Closes #1014 
I know it's fixed in a larger incoming PR but we shouldn't have anything like this hanging around.

fixing formatting in debugf

---

CHANGELOG.md
cmd/notary/integration_test.go
utils/keys.go
utils/keys_test.go

The logic to infer the GUN from the `path` PEM header will panic when importing an exported delegation key.  This is because the path will look like `tuf_keys/<KEY_ID>` and this logic will attempt to shorten an empty string slice: https://github.com/docker/notary/blob/v0.4.2/utils/keys.go#L114
This only affects v0.4.2 - the integration test I added here passes on master without any other code changes.  Targeting a v0.4.3 hotfix, if we are to release one.
Closes #1066

Fix delegation key import/export GUN inference logic

---

trustpinning/certs.go
trustpinning/certs_test.go

This adds support for explicit wildcard suffixes in root (leaf) certificates of the form `prefix*`. 
I considered doing something more flexible using `filepath.Match` but I think this more conservative form is safer and (probably) just as useful. It would be easy to change in the future if more flexibility (e.g. `docker.io/*/test`) is needed. 
Note the wildcard `*` indicator is required to avoid accidentally using wildcard certs (e.g. `docker.io/test` and `docker.io/test2`).
Fixes #883 
Possibly addresses #914 as well?

Support wildcard CNs in root leaf certificates

---

server/handlers/changefeed.go
server/handlers/changefeed_test.go
server/handlers/default.go
server/handlers/default_test.go
server/server.go
server/storage/sql_models.go
utils/http.go

When using Notary as a library, I ran into some visibility issues that I've addressed here.
I'm a little uneasy about this PR because I can only justify it from my own experience, but I don't think there's anything egregious here. Personally, I think this changeset a slight readability improvement, regardless.

Minor refactoring (nicer lib usage)

---

docs/running_a_service.md

https://github.com/docker/notary/blob/master/docs/running_a_service.md says 
```
Notary signer database user: SELECT, INSERT, DELETE
```
and it is missing `UPDATE` priv. 
From signer log:
```
(Error 1142: UPDATE command denied to user 'signer'@'172.17.0.3' for table 'private_keys') 
```
Captured SQL queries:
```
2017-03-01T08:52:40.905616Z	   88 Prepare	UPDATE `private_keys` SET `last_used` = ?  WHERE (`private_keys`.deleted_at IS NULL OR `private_keys`.deleted_at <= '0001-01-02') AND ((key_id = ?))
2017-03-01T08:52:40.905677Z	   88 Execute	UPDATE `private_keys` SET `last_used` = '2017-03-01 08:52:40.90511'  WHERE (`private_keys`.deleted_at IS NULL OR `private_keys`.deleted_at <= '0001-01-02') AND ((key_id = 'f3b0734272c75bbee386d780a6a01ad2a0c78e3f6e4d98f0aaee32efa9f3b508')) …
```

Docs: notary signer user requires UPDATE priv.

---

client/client.go
client/client_test.go
client/helpers.go
cmd/notary/tuf.go

This work depends on the work done in https://github.com/docker/notary/pull/1094, allowing us to inject a `remote store` and a `cache` in a `NotaryRepository` object.
Since this PR is stacked on top of https://github.com/docker/notary/pull/1094 which just got merged, make sure you pull the latests changes. 
We are now initializing the repository when publishing, if needed. We do this for three reasons:
1. reduce the amount of operations necessary for notary users to setup their repo
2. avoid metadata corruption when calling init several times on the same repo - https://github.com/docker/notary/issues/1071
3. give more flexibility on how to initialize
The lazy initialization is done either from scratch by `NotaryRepository.Initialize()` when starting from a blank state or by …

Notary repository lazy initialization

---

cmd/notary/tuf.go

When doing auth, add the path of "tuf URL" before "/v2" for ping client 
For more details please refer to #1107 
Signed-off-by: Tan Jiang <jiangd@vmware.com>

fixes #1107

---

CONTRIBUTING.md

This fixes issue #1148 
Sometimes GitHub is finicky with their markdown. Replacing the space fixes the markdown formatting issues.
Signed-off-by: Wilson Ding <hello@wilsonding.com>

Fixes #1148 incorrect markdown formatting

---

migrations/migrate.sh
server.Dockerfile
signer.Dockerfile

Signed-off-by: Ashwini Oruganti <ashwini.oruganti@gmail.com>

Upgrade and pin mattes/migrate to the v3.0.0 tag

---

client/client.go
client/client_test.go
cmd/notary/integration_test.go
cmd/notary/tuf.go

Expose targets custom data in the NotaryRepository API

---

utils/configuration.go
utils/configuration_test.go
vendor.conf
vendor/github.com/go-sql-driver/mysql/README.md
vendor/github.com/go-sql-driver/mysql/buffer.go
vendor/github.com/go-sql-driver/mysql/collations.go
vendor/github.com/go-sql-driver/mysql/connection.go
vendor/github.com/go-sql-driver/mysql/const.go
vendor/github.com/go-sql-driver/mysql/driver.go
vendor/github.com/go-sql-driver/mysql/dsn.go
vendor/github.com/go-sql-driver/mysql/errors.go
vendor/github.com/go-sql-driver/mysql/infile.go
vendor/github.com/go-sql-driver/mysql/packets.go
vendor/github.com/go-sql-driver/mysql/rows.go
vendor/github.com/go-sql-driver/mysql/statement.go
vendor/github.com/go-sql-driver/mysql/utils.go

Closes #328 
Also updates the mysql driver to a newer release
Signed-off-by: Ashwini Oruganti <ashwini.oruganti@gmail.com>

Auto-parse the DB URL and add parseTime=true if the backend is mysql

---

cmd/notary/tuf.go

This change came in here: https://github.com/docker/notary/commit/25cd29c8b0df3e8ae3cc0d8427c213f760b5e76f
But I can't really tell why. It breaks scripting tuf commands (if you're not running in a terminal, all requests are anonymous to the server).
I think #861 is the proper solution, but for now it's nice to be able to script it via stdin.

Allow scripting the terminal in TUF commands

---

tuf/signed/sign_test.go
tuf/signed/verifiers_test.go
tuf/utils/x509_test.go

OpenSSL-FIPS does not allow RSA keys to be generated if the key size is less than 1024. So the RSA key sizes in tests have been updated to prevent them from failing if Notary is made FIPS compliant.
Signed-off-by: Ali Yousuf <aly.yousuf7@gmail.com>

Change RSA key size to at least 1024 bits

---

Dockerfile
cross.Dockerfile
server.Dockerfile
signer.Dockerfile

Currently in beta1, wanted to give it a spin on our CI just in case we find any issues to fix on the notary or golang side (we found one in docker by testing DCT: https://github.com/docker/docker/pull/29030)
We can bump this as new betas are released, and eventually this can be the PR for the final golang 1.8.0 release bump tracked for early 2017.
**Update**: bumped to golang 1.8.1

Bump to golang 1.8.1

---

fixtures/regenerateTestingCerts.sh

This can be used to regenerate testing certs for postgres db connections.
Depends on #1160

Update test cert generation script for postgresql

---

cmd/notary/keys.go
cmd/notary/keys_test.go
cryptoservice/crypto_service.go
tuf/utils/x509.go

It also gains the `-o`/`--output` flag, which if provided will cause the public and private key to be output to the filepath specified in the flag with the .pub and .priv file extensions respectively.

`notary key generate` shouldn't be restricted to root keys

---

client/client.go
client/client_test.go
cmd/notary/integration_test.go
cmd/notary/tuf.go
cmd/notary/tuf_test.go
tuf/signed/verify.go
tuf/signed/verify_test.go
tuf/utils/x509.go

Supports initializing a notary repository by passing in a root certificate alone with the corresponding root key. This would make wildcard certificate trust pinning usable as an existing trusted certificate can now be included in `root.json` metadata.
usage : `notary init [ GUN ] --rootkey path/to/key.key --rootcert path/to/cert.crt` 
`--rootcert` can only be used when `--rootkey` is specified. 
related works include #821 and #883.

Support for initializing repository with root certificate 

---

cmd/notary/integration_test.go
cmd/notary/main.go
utils/keys.go

- makes `warn` the default log level on notary CLI
- increases the `-v` log level from `error` to `info`
- bumps up key import/export failure logs from `info` to `warn`
cc @cyc115 @ecordell 
Closes #1162, #1178
Ex: here's what an offline `notary list` looks like now if there's a cache with a valid timestamp:
```
🐳 $ ./notary -s https://notary.docker.io list docker.io/library/alpine
ERRO[0000] could not reach https://notary.docker.io: Get https://notary.docker.io/v2/: dial tcp: lookup notary.docker.io on [::1]:53: read udp [::1]:56941->[::1]:53: read: connection refused
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely
NAME               DIGEST …
```

Bump up default log level, key import/export logs

---

client/client.go
storage/httpstore.go

This introduce and explicit nil-check on the metadata store in
`NewNotaryRepository()`, to match the docstring and to avoid further
panics at runtime.
It also clarify the default behavior in case of a nil remote store and of
a nil roundtripper.
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>

client: improve constructor checks and docs

---

storage/httpstore.go
storage/httpstore_test.go

Fixed some of the `httpstore` downloading logic to limit the size of the response bodies we're willing to read.
We should also fix `ImportKeys` and the `notary verify` command, but those are slightly bigger changes, so am splitting them out.

Do not ioutil.ReadAll anything without limiting the size.

---

tuf/testutils/repo.go

In the test repo generation code, when we serialized delegation metadata, we [serialized using canonical JSON serialization](https://github.com/docker/notary/blob/master/tuf/testutils/repo.go#L165), which does not match what actually gets [done in the client](https://github.com/docker/notary/blob/master/client/helpers.go#L270), or the rest of the testutil non-delegation serialization, or for [calculating the checksum in the snapshot](https://github.com/docker/notary/blob/master/tuf/tuf.go#L867).
Fix this to make it consistent with actual behavior.
(We want to migrate to doing canonical JSON everywhere at some point - see https://github.com/docker/notary/issues/481 - but until that happens we should keep the test generation and actual generation consistent).
Note that this should allow us …

Make testutils metadata generation consistent with how metadata is produced by the client

---

signer/keydbstore/cachedcryptoservice.go

Changed `lock` to be of type `sync.RWMutex` in `cachedKeyService` in  notary/signer/keydbstore/cachedcryptoservice.go and introduced a read lock around read access to the map `cachedKeys` to avoid race conditions when the map is being read and written at the same time.
This fixes the issue https://github.com/docker/notary/issues/1194.

Fixed potential race condition in cachedKeyService

---

tuf/utils/pkcs8.go

Adds [this comment](https://github.com/docker/notary/pull/1130#discussion_r129042988) to the source so we don't ever lose track of the rationale

pkcs8: add comment about padding during unmarshal

---

MAINTAINERS_RULES.md

This document formalizes the rules I emailed in the maintainer invitations we've sent, and formalizes the process for adding and removing maintainers (I've just written out what we've already been doing).
Given this is the first publication of these rules, I'd like to get unanimous approval for this initial version.
cc @ecordell @HuKeping @cyli @riyazdf 

formalizing the maintainers rules into a file

---

cmd/notary/tuf.go

This should fix scripts that never end due to a user/pass prompt.

add timeout on docker username

---

client/client.go

type the No valid trust data error

---

server/handlers/changefeed.go
server/handlers/default.go
server/storage/errors.go
server/storage/memory.go
server/storage/mysql_test.go
server/storage/postgresql_test.go
server/storage/rethink_realdb_test.go
server/storage/rethinkdb.go
server/storage/rethinkdb_models.go
server/storage/rethinkdb_test.go
server/storage/sql_models.go
server/storage/sqldb.go
server/storage/storage_test.go

changefeed for rethinkdb

---

client/client.go
client/tufclient.go

Signed-off-by: Tibor Vass <teabee89@gmail.com>
Unless I'm mistaken, this was not meant to be exported.

Keep TUFClient private as tufClient

---

Jenkinsfile

Signed-off-by: Robb Kistler <robb.kistler@docker.com>

jenkinsfile: skeleton to test github integration

---

client/backwards_compatibility_test.go
client/client.go
client/client_test.go
client/interface.go
cmd/notary/keys.go
cmd/notary/keys_test.go
cmd/notary/repo_factory.go
cmd/notary/tuf.go
storage/filestore.go
utils/configuration_linux_test.go
utils/configuration_test.go

- creates a `Repository` interface to standardize `client.NotaryRepository`
- fixes `InitializeWithCertificate` to not take a notary repository as an argument
Part of #1139, originally stolen from `endophage/client_interface` branch

Notary client interface type

---

client/backwards_compatibility_test.go
client/client.go
client/client_test.go
client/client_update_test.go
client/delegations.go
client/witness.go
cmd/notary/delegations.go
cmd/notary/keys.go
cmd/notary/keys_test.go
cmd/notary/repo_factory.go
cmd/notary/tuf.go
trustmanager/remoteks/server_test.go

Also fixes a small bug with SetLegacyVersions.
Signed-off-by: Tibor Vass <teabee89@gmail.com>

Remove `Notary` from Repository constructor functions

---

server/handlers/validation.go
storage/filestore.go

There was an update to lint!  Fix the extraneous `else` clauses appropriately.

fix updated linting to remove redundant else clauses

---

Dockerfile
cross.Dockerfile
server.Dockerfile
signer.Dockerfile

Bumps the Go version used to 1.8.4, which contains security fixes;
https://groups.google.com/forum/#!topic/golang-announce/1hZYiemnkdE
This will currently fail, as the images are not live yet on Docker Hub, but they're currently building, so should be available shortly(r)(tm)
https://hub.docker.com/r/library/golang/tags/
ping @riyazdf @endophage

Bump Go to 1.8.4

---

MAINTAINERS
MAINTAINERS.ALUMNI

@dmcgowan pinged you about this a while ago. Please LGTM for the sake of protocol. Thanks!
maintainers: I'll merge this with just Derek's LGTM

remove derek as a maintainer

---

cmd/notary/tuf.go
cmd/notary/tuf_test.go

In case of automation it may not be possible to prompt the user
for username and password. To provide a way to pass username and
password we introduce the NOTARY_AUTH environment variable through
which username and password can be passed. Username and password
must be separated by ':' and base64 encoded.
The following example shows how to set username and password:
> export NOTARY_AUTH="$(echo -n "me:mysecretpassword" | base64)"
Decoding:
> echo $NOTARY_AUTH | base64 -d
me:mysecretpassword
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

Introduce env. variable NOTARY_AUTH for setting username & password

---

README.md

remove please and change our to Notary's in README

---

cmd/notary/integration_test.go
cmd/notary/keys_test.go
trustmanager/keys.go

return errors for invalid key pem blocks

---

tuf/tuf.go

remove warning when checking if delegation certs have expired

---

README.md

Hello there! :)
I'm just simplifying the building and installation instructions to what worked for me.
Let me know what you think!

Simplify client building and installation instructions.

---

trustmanager/yubikey/pkcs11_linux.go

I added some filepaths to the shared `libykcs11` library may be found on Fedora after installing `yubico-piv-tool`.
Signed-off-by: Trishank K Kuppusamy <trishank.kuppusamy@datadoghq.com>

Add some filepaths on Fedora where libykcs11 may be found

---

MAINTAINERS
docs/reference/client-config.md
docs/service_architecture.md

Updates a few last places to the proper repo name.
For the CDN images: GH will work even with `docker/notary` in the URL but figured we should update anyway - I've tested the images and it works with the new naming.

update MAINTAINERS file with updated repo name, update github cdn urls

---

Dockerfile
buildscripts/cross.sh
cross.Dockerfile
escrow.Dockerfile
server.Dockerfile
signer.Dockerfile
vendor.conf
vendor/github.com/miekg/pkcs11/README.md
vendor/github.com/miekg/pkcs11/const.go
vendor/github.com/miekg/pkcs11/pkcs11.go
vendor/github.com/miekg/pkcs11/pkcs11.h
vendor/github.com/miekg/pkcs11/pkcs11f.h
vendor/github.com/miekg/pkcs11/pkcs11go.h
vendor/github.com/miekg/pkcs11/pkcs11t.h
vendor/github.com/miekg/pkcs11/types.go

This is a security fix release of Go, see https://go-review.googlesource.com/c/go/+/73392
Some of the fixes may be relevant for Notary.

Update Go to 1.9.4

---

Dockerfile

On s390x these are needed, not sure why there is a difference but
it is a harmless addition.

Add python setuptools to Dockerfile

---

vendor.conf
vendor/github.com/docker/go-connections/tlsconfig/certpool_other.go
vendor/github.com/docker/go-connections/tlsconfig/config.go

If this is approved before https://github.com/theupdateframework/notary/pull/1306, ideally it would be included in the 0.6.0 release as well and I'll update the changelog and relevant branches.

Bump the go-connections vendor so that we disable insecure RSA key exchange ciphers and require TLS >= 1.2

---

cmd/notary/main.go

There is a few case where home could not be found (and would not be
needed). Especially as this piece of code is only there to set a
default value for a flag.
cc @cyli @n4ss @endophage 
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Don't error out in case home cannot be found

---

docs/reference/client-config.md

Documents the environment variable introduced in https://github.com/theupdateframework/notary/pull/1246.  Fixes https://github.com/theupdateframework/notary/issues/1292.

Document the NOTARY_AUTH environment variable

---

server.minimal.Dockerfile
signer.minimal.Dockerfile

Update minimal dockerfiles to use multi-stage builds to achieve minimalness

---

fips.go
tuf/utils/x509.go
tuf/utils/x509_test.go

The best test we currently have for whether Notary is running in a FIPS
compliant environment is whether the MD5 hash function is registered when
crypto/md5 is linked in to the program. This function is not available
in FIPS mode as it is not an allowed hash function.

Rework the FIPS mode detection

---

README.md

Sorry, a bit OCD but it was getting to me :)

Be consistent about Notary vs notary

---

server.Dockerfile
signer.Dockerfile

Because we deleted the apk cache and then did apk operations, a large
warning was appearing. Reorder the operations so the build logs are cleaner.

Remove apk warnings

---

docs/Dockerfile
escrow.Dockerfile
server.Dockerfile
server.minimal.Dockerfile
signer.Dockerfile
signer.minimal.Dockerfile

This field is deprecated, and maintaining Dockerfiles is the
responsibility of all the Notary maintainers.

Remove MAINTAINERS from Dockerfiles

---

cmd/notary-signer/dump_linux.go
cmd/notary-signer/dump_unsupported.go
cmd/notary-signer/main.go

This disables
- core dumps, which might contain keys
- ability to ptrace the process which may allow keys to be read
This is not enabled in the debug mode.

Set the Notary Signer to be non dumpable in Linux

---

cmd/notary/repo_factory.go
cmd/notary/tuf.go
cmd/notary/tuf_test.go

Fixes https://github.com/theupdateframework/notary/issues/1308
Signed-off-by: Michael Hough <michaelh@uk.ibm.com>

Add permission to ConfigureRepo function

---

tuf/data/keys.go

This really confused me today, as it only appears to copy part of
the private key. As stated in other files we are storing public key
concatenated with public key here.
We did not need to do this as the second half of an ed25519 private
key is the public key, so documenting it definitely reduces confusion.

Add another note about serialization of ed25519 keys

---

server/server_test.go
signer/client/signer_trust.go
trustmanager/remoteks/client.go

You have to call the cancellation, or it will leak if it is not called,
in the common case when the timeout is not reached.
The docs say "Canceling this context releases resources associated with it,
so code should call cancel as soon as the operations running in this Context
complete".

Do not leak cancellations for contexts

---

Dockerfile
cross.Dockerfile
escrow.Dockerfile
server.Dockerfile
server.minimal.Dockerfile
signer.Dockerfile
signer.minimal.Dockerfile

go1.10.3 (released 2018/06/05) includes fixes to the go command, and the
crypto/tls, crypto/x509, and strings packages. In particular, it adds minimal
support to the go command for the vgo transition. See the Go 1.10.3 milestone
on our issue tracker for details;
https://github.com/golang/go/issues?q=milestone%3AGo1.10.3

Bump Golang to 1.10.3

---

Dockerfile
Makefile
cross.Dockerfile

`github.com/GoASTScanner/gas` has been renamed to `github.com/securego/gosec`, and the executable also renamed `gosec`.  
This PR fixes all the imports/installs so that CI works again.
cc @justincormack

Fix gas check (was renamed to gosec)

---

tuf/utils/pkcs8.go

The code checker, gosec, has started flagging the import of crypto/sha1
as potentially weak crypto. It is being used as the hash function for
PBKDF2 when keys are password protected.
In the short term I think removing the warning is fine as it restores
the status quo; need to look further if we really need this code.

Add import of sha1 to gosec whitelist

---

client/backwards_compatibility_test.go
client/client.go
client/client_test.go
client/client_update_test.go
client/delegations.go
client/interface.go
client/reader.go
client/tufclient.go
cryptoservice/crypto_service.go
server/handlers/default_test.go
storage/httpstore.go
storage/httpstore_test.go
storage/interfaces.go

Refactor the notary client library to have a separate reader and loader that may be easier to use for clients that do not need any publishing capabilities.
Originally proposed something similar in https://github.com/theupdateframework/notary/issues/968 - this just makes it easier to set up a downloading client that can read to an in-memory cache, or just something that will load from cache without having to provide a CryptoService, etc.
The plan is, if this PR passes design and code review, for a new PR converting all the `client_update_tests` to just use the `LoadTUFRepo` function and an in-memory cache.
cc @justincormack

Notary client refactor - simpler reader interface

---

Makefile

This was I guess to stop builds pre Go 1.7 but that is very old
now, and the check breaks on every new Go release. I think we
can just document any requirements instead.

Do not check Go version user is building with

---

Dockerfile
cross.Dockerfile
escrow.Dockerfile
server.Dockerfile
server.minimal.Dockerfile
signer.Dockerfile
signer.minimal.Dockerfile

Includes denial of service fix on TLS connections, and other security fixes.
1.10.7 images are not out yet, and 1.10.6 has a bug so that breaks build, so need to wait for 1.10.7 images.

Update to Go 1.10.8

---

client/client.go
client/tufclient.go

This commit fixes the format specifier type for logging statements.
Inspired by: https://github.com/theupdateframework/notary/issues/1070
Signed-off-by: Simarpreet Singh <simar@linux.com>

client: fix logger format types for variables

---

README.md
buildscripts/env.list
docs/README.md
docs/service_architecture.md
notarysql/postgresql-initdb.d/pg_hba.conf

This PR replaces old HTTP links in various places (eg: README, docs ...) by secure, correct HTTPS links.

Update deprecated links

---

Dockerfile
cmd/notary-server/main_test.go
cross.Dockerfile
escrow.Dockerfile
server.Dockerfile
server.minimal.Dockerfile
signer.Dockerfile
signer.minimal.Dockerfile
tuf/data/roles_test.go

Alternative to https://github.com/theupdateframework/notary/pull/1396, but let me know if it's acceptable to switch to a different base-image (instead of the official Go image)
Added an extra commit to switch to the golang-cross image, and rebased @justincormack's PR on that, then bumped Go to 1.11.5
Note that the version built on Go 1.11 requires `libtool` to be installed on macOS in order to run the binary;
On Go 1.10:
```
otool -L ./cross/darwin/amd64/notary
./cross/darwin/amd64/notary:
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1253.0.0)
/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57336.1.9)
/usr/lib/libSystem.B.dylib (compatibility …
```

Bump golang 1.11, and switch to dockercore/golang-cross for cross-compiling

---

CODE_OF_CONDUCT.md

Currently, when we access the modified pages with **HTTP**, it is
redirected to **HTTPS** automatically. So this commit aims to
replace **HTTP** to **HTTPs** for security.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

Replacing 'HTTP' by 'HTTPS' for securing links

---

tuf/builder.go
tuf/data/roles.go
tuf/utils/utils.go
utils/auth_test.go

Although it is spelling mistakes, it might make an affects while reading.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

Remove the duplicated words in code comments

---

cmd/notary-server/main.go
cmd/notary-signer/main.go
cmd/notary/main.go

My lunch project of the day;
With this applied, all binaries now allow printing the version:
```bash
make notary-dockerfile && docker run --rm notary sh -c 'make client && /go/src/github.com/theupdateframework/notary/bin/notary --version && /go/src/github.com/theupdateframework/notary/bin/notary  version' || echo "version failed"
notary Version: 0.6.1, Git commit: d5b73be7, Go version: go1.12.7
make server-dockerfile && docker run --rm notary-server --version || echo "--version failed"
make signer-dockerfile && docker run --rm notary-signer --version || echo "--version failed"
```

Add Golang version to version output, and add '--version' flag to binaries

---

vendor.conf
vendor/github.com/miekg/pkcs11/go.mod
vendor/github.com/miekg/pkcs11/release.go

this package now tags releases; no significant changes otherwise
full diff: https://github.com/miekg/pkcs11/compare/553cfdd26aaafe851ca66a5e8015f0decb6b5a1e...v1.0.2

bump miekg/pkcs11 v1.0.2

---

cmd/notary-server/main.go

This was a false positive, as no server is started unless `-debug` is enabled.
Also see https://github.com/theupdateframework/notary/pull/1505, which fixes CI to print the actual failure

gosec: ignore  G108: Profiling endpoint automatically exposed

---

cmd/escrow/main.go

This fixes the tests being broken on Go 1.13 and up, which is caused by a change
in Go 1.13: https://golang.org/doc/go1.13#testing
> Testing flags are now registered in the new Init function, which is invoked by
> the generated main function for the test. As a result, testing flags are now only
> registered when running a test binary, and packages that call flag.Parse during
> package initialization may cause tests to fail.
Before this change:
make test
ok  	github.com/theupdateframework/notary/client/changelist	(cached)
flag provided but not defined: -test.testlogfile
Usage of /var/folders/c_/vjh56sc12fd2b_q2n02_lt140000gn/T/go-build270388911/b229/escrow.test:
-config string
path to configuration file; supported formats are JSON, YAML, and TOML (default "config.toml")
...
FAIL
make: *** …

Fix "make test" broken on Go 1.13

---

.gitignore
Makefile

Before this, `make lint` would fail, but the output of the linter would be
discarded, making it unclear what caused the failure:
docker build -t notary_client . && docker run -it --rm -e NOTARY_BUILDTAGS=pkcs11 notary_client sh -c 'make lint'
...
[gosec] 2019/10/16 11:11:04 Checking file: /go/src/github.com/theupdateframework/notary/utils/http.go
make: *** [Makefile:106: lint] Error 1
This problem occurred, because there was an actual linting error, and
the code to check for failures did so by checking the output of the
csv file to be empty;
test -z "$$(cat gas_output.csv | tee /dev/stderr)"
In this case, it was not, and the file contained:
/go/src/github.com/theupdateframework/notary/cmd/notary-server/main.go,8,Profiling endpoint is automatically exposed on /debug/pprof,HIGH,HIGH,"_ …

Fix gosec linter results not being printed

---

Dockerfile
cross.Dockerfile
escrow.Dockerfile
migrations/README.md
server.Dockerfile
server.minimal.Dockerfile
signer.Dockerfile
signer.minimal.Dockerfile

Bump golang 1.12.10 (CVE-2019-16276)
=====================================================
go1.12.10 (released 2019/09/25) includes security fixes to the net/http and net/textproto
packages. See the Go 1.12.10 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.10
Bump golang 1.12.9
=====================================================
go1.12.9 (released 2019/08/15) includes fixes to the linker, and the os and math/big packages.
See the Go 1.12.9 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.9
Bump golang 1.12.8 (CVE-2019-9512, CVE-2019-9514)
=====================================================
go1.12.8 (released 2019/08/13) includes security fixes to the net/http and net/url packages. …

Bump golang 1.12.10 (CVE-2019-9512, CVE-2019-9514, CVE-2019-16276)

---

Dockerfile
cross.Dockerfile
escrow.Dockerfile
server.Dockerfile
server.minimal.Dockerfile
signer.Dockerfile
signer.minimal.Dockerfile

Golang 1.12.12
-------------------------------
full diff: https://github.com/golang/go/compare/go1.12.11...go1.12.12
go1.12.12 (released 2019/10/17) includes fixes to the go command, runtime,
syscall and net packages. See the Go 1.12.12 milestone on our issue tracker for
details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
Golang 1.12.11 (CVE-2019-17596)
-------------------------------
full diff: https://github.com/golang/go/compare/go1.12.10...go1.12.11
go1.12.11 (released 2019/10/17) includes security fixes to the crypto/dsa
package. See the Go 1.12.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.11
[security] Go 1.13.2 and Go 1.12.11 are released
Hi gophers,
We have just released Go 1.13.2 and Go 1.12.11 to address …

Update Golang 1.12.12 (CVE-2019-17596)

---

.circleci/config.yml

YOLO; https://discuss.circleci.com/t/default-machine-executor-image-update/29308 mentioned CircleCI now has Docker 18.09, so let's see if this works

CircleCI: update image, and use BuildKit

---

Makefile

CI was quite noisy, and probably could do without the `-debug` option (I think it can still be enabled by setting a `DEBUG` env-var if needed)

Makefile: disable debug to make CI more readable

---

client/client_test.go
cmd/notary/integration_test.go
cmd/notary/tuf.go
tuf/signed/sign_test.go

Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

Remove duplicated words

---

development.mysql.yml
docker-compose.yml

Bumped the mariadb container used in docker-compose to 10.4 docker image.

Bump mariadb from 10.1.28 to 10.4

---

client/changelist/file_changelist.go
cmd/notary/keys.go
cmd/notary/util.go
storage/filestore.go

Carrying the first commit of https://github.com/theupdateframework/notary/pull/1537 (updated the commit message with a description)

Fix gosec linting errors (fix G306 and G307)

---

CHANGELOG.md
MAINTAINERS_RULES.md

1. "ptraceable" to "traceable" in line 5.
2. "preferrable" to "preferable" in line 32.

Fix some typos in markdown docs

---

trustmanager/yubikey/pkcs11_darwin.go

`/opt/homebrew` is where pkcs11 libraries are put by default on arm64 https://github.com/Homebrew/install/blob/b62804e014a2d31216e074398411069688517a79/install.sh#L29-L32
I could also put `/usr/local/lib` and `/opt/homebrew` behind different arch buildtags to handle the case where a user could have both native and rosetta toolchains better. But I'm not sure if some users might prefer to still manually use the old path in arm64 as well. I haven't verified that any of this works under rosetta at all.
@justincormack 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

yubikey: add library path for arm64

---

cryptoservice/fuzz/fuzz.go

This PR adds a fuzzer that targets `GetPrivateKey()`.
The fuzzer runs both locally and on oss-fuzz's infrastructure as well. I suggest integrating Notary into oss-fuzz which will allow Google to run this fuzzer and future fuzzers on their platform continuously. When a bug is found by oss-fuzz, the maintainers on the contact list receive a detailed bug report via email. 
To be part of the project is free. It is expected that the bugs are fixed, so that the resources put into running the fuzzers go to good use.
I will be happy to integrate Notary into oss-fuzz. All I need are the email addresses of maintainers that need to receive the bug reports.

Added fuzzer for cryptoservice

---

Dockerfile
cross.Dockerfile

The build was failing due to a breaking change to `goclyclo`.
Recently (18 days ago at the time of this writing) `gocyclo` updated to `go1.16` and started using it's `io/fs` package. Due to this `make cross` breaks as it depends on Go `1.12.5`, I took liberty to update it to the latest go `1.13.5` release.
I also had to move the enabling of Go modules to be able to install gocyclo at a specific version/commit.
Also worked a bit on the cache-ability of layers in the image by splitting some RUN statements.

BUGFIX: Resolve build error with 'make cross'

---

buildscripts/dbtests.sh
development.mysql.yml
development.postgresql.yml
server/storage/concurrent_sqldb_test.go
server/storage/mysql_test.go
server/storage/postgresql_test.go
server/storage/sqldb.go
server/storage/sqldb_test.go

There is a race condition in the `UpdateMany` method on `SQLStorage`. This race condition means that if the `POST /v2/{gun}/_trust/tuf/` endpoint is called concurrently, tuf_files with the same gun/role/version in different requests can silently overwrite each other. This can cause data corruption if a snapshot is generated that references a file that is later overwritten.
The current code has two measures in place to prevent this from happening: a unique index on the gun/role/version combination, and an up-front check that there are no existing files with the same gun/role and an equal or greater version to those being created. The up-front check doesn't use any locking so it doesn't prevent concurrent requests with files that would match. The unique index should be enough, but at the …

Fix race condition in `UpdateMany`

---

server/handlers/default.go

In golang 1.17 [a change was made](https://go.dev/doc/go1.17#minor_library_changes) to remove anything preceding a slash from the filename field of the Content-Disposition header. This causes a problem with notary since it's using the filename field for the role value. This fix changes the parsing of the header value so it grabs the raw filename value instead of using the method that removes the base part of the filename.
This is also outlined in this issue:
https://github.com/notaryproject/notary/issues/1630

Fix role parsing in golang 1.17+

---

.circleci/config.yml
server/storage/sqldb.go

Static builds are broken on `master` because of a change introduced in #1636 which added a dependency on the sqlite library which requires cgo. We don't actually support sqlite outside of tests so this PR removes the dependency. I've also added a CI step to build the static binaries to make sure this doesn't happen again.
We discovered this at Docker because [we use the static binaries to build](https://github.com/docker/notary-official-images/blob/master/notary-server/Dockerfile#L15) the [Docker Official Image](https://hub.docker.com/_/notary) for Notary.

Fix static binary build

---

server/storage/tuf_store.go
server/storage/tuf_store_test.go

`TUFMetaStorage` uses an in-memory cache to store all retrieved metadata files. This cache has a few problems:
1. It doesn't have any sort of limit on its size so it will grow indefinitely as more content is retrieved
2. Entries in the cache are not deleted when `Delete` is calls on a `TUFMetaStorage` instance. This means the cache can hold entries that have been deleted from the underlying storage (there seem to be tests for this behavior so could this be for a reason?)
3. It isn't safe for concurrent use, see #1613.
I've taken the scorched-earth approach of simply removing this cache. After #1639 it should be fast to get these files from the database each time. I'll test this on Docker's production instance before merging it to check the performance is still OK.

Remove unbounded cache

---

buildscripts/testclient.py

This one-line change is a little bit less clean-looking than I'd like, but this makes sure it works on both Python 2 _and_ Python 3. :smile:
I worked this up (and validated it) via https://github.com/docker/notary-official-images/pull/29. :eyes: :metal:

Update "testclient.py" to work on Python 3

---

README.md

The PR addresses #1684 and achieve the following
1. Call out that the repository is scoped to the TUF implementation. 
2. Remove the upper case 'Notary' in places where it can and reference the client and server components to avoid confusion with the 'Notary Project'
Please provide feedback since I'm doing this with the best context I have and there might be areas or discussions I have missed.

Update readme to align with TUF

---

MAINTAINERS

As per @justincormack suggestion, I am nominating @jonnystoten as a maintainer for this repository. According to Justin, Jonny will be maintaining the old implementation of Notary used by Docker Content Trust. I am leaving to the current maintainers to approve this change. Once approved, we need to update the CODEOWNERS (see #1673) with Jonny's handle.

Nominating jonnystoten for notary repo maintainer

---

CODEOWNERS
MAINTAINERS
MAINTAINERS.ALUMNI

Addresses https://github.com/notaryproject/.github/issues/66, https://github.com/notaryproject/.github/issues/67, https://github.com/notaryproject/.github/issues/68, and https://github.com/notaryproject/.github/issues/69

Org maintainers update
