notaryproject/notary

signer/rufus_trust.go
Staging this here until rufus update is in.
=> populate key and signature type from rufus's Algorithm field

client/cli_crypto_service.go, client/client.go, client/client_test.go, trustmanager/filestore.go, trustmanager/filestore_test.go
=> Test improvements

Dockerfile
I am OCD about having nice dockerfiles
=> cleanup dockerfile

circle.yml
Remove remaining references to old go version
=> Remove circle old go version

client/changelist/changelist.go, client/changelist/files_changelist.go, client/client.go
Do not use fmt.Println in client, shows up in UX of importers
=> Use logrus instead of fmt.Println

docker-compose.yml, notary-server-Dockerfile, notary-signer-Dockerfile
=> Working docker build/docker compose

Makefile, coverage.sh
Adding script to make it easy to compute coverage over all packages.
=> Adding script to output coverage over all packages

cmd/notary-server/config.json, cmd/notary-server/main.go, cmd/notary/tuf.go, server/storage/database.go, server/storage/database_test.go
This is why I need a way to unit test against a real database. The queries were broken. Had to revert to an earlier form that I'm not particularly happy with but it'll work.
=> fixing database queries

cryptoservice/crypto_service_test.go, cryptoservice/unlocked_crypto_service_test.go, trustmanager/keyfilestore_test.go
@diogomonica @NathanMcCauley 
Increase test coverage in cryptoservice and trustmanager packages
=> New unit tests

client/client.go, client/client_test.go, server/timestamp/timestamp.go, server/timestamp/timestamp_test.go
=> fixing timestamps, clearing changelists, and the Adding target byte log

client/client.go, client/client_test.go
=> updating error messages

Godeps/Godeps.json, Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify.go, client/client_root_validation_test.go, keystoremanager/keystoremanager.go, trustmanager/x509filestore.go, trustmanager/x509utils.go, trustmanager/x509utils_test.go
Changes the validate root logic to use TUF for rotation.
@NathanMcCauley
=> Cooking the tofu to support rotations

cmd/notary-server/dev-config.json, notarymysql/initial.sql, server/handlers/default.go, server/storage/database.go, server/timestamp/timestamp.go
=> fixing timestamp errors on list

Godeps/_workspace/src/github.com/endophage/gotuf/client/client_test.go, client/client.go, client/helpers.go, server/handlers/default.go, server/storage/memory.go
=> WIP general cleanup

Godeps/Godeps.json, Godeps/_workspace/src/github.com/endophage/gotuf/README.md, Godeps/_workspace/src/github.com/endophage/gotuf/data/types.go, client/client.go, server/server.go
=> update default expiry times to those agreed on

trustmanager/x509utils.go, trustmanager/x509utils_test.go
Changing certificate expiration time to 10 years
=> Changing certificate expiration time to 10 years

keystoremanager/keystoremanager.go, trustmanager/x509filestore.go, trustmanager/x509filestore_test.go, trustmanager/x509store.go, trustmanager/x509utils.go
Fixed but with loadCertsFromDir, added tests and more debugging.
@endophage @NathanMcCauley 
=> Fixed but with loadCertsFromDir and added tests

Godeps/Godeps.json, Godeps/_workspace/src/github.com/endophage/gotuf/client/client.go, Godeps/_workspace/src/github.com/endophage/gotuf/store/httpstore.go, client/client.go
=> updating gotuf dep with some better http error handling.

client/client.go, cryptoservice/crypto_service.go, trustmanager/keyfilestore.go
=> better error handling for invalid password

cryptoservice/crypto_service.go, trustmanager/keyfilestore.go
Fixes mismatched expectation in docker client
=> Return invalid password when cannot retrieve passphrase

trustmanager/keyfilestore.go
=> Add missing use of invalid passphrase error

proto/signer.pb.go, proto/signer.proto, signer/api/rpc_api.go, signer/api/rsa_hardware_crypto_service.go, signer/signer_trust.go, trustmanager/x509utils.go
Updated protos and fixed rsa hardware signer bug.
=> Proto update

pkg/passphrase/passphrase.go
@dmcgowan 
Signed-off-by: Nathan McCauley <nathan.mccauley@docker.com>
=> Abridge key ids on print, warn about key generation

Godeps/Godeps.json, Godeps/_workspace/src/github.com/endophage/gotuf/client/client.go, Godeps/_workspace/src/github.com/endophage/gotuf/signed/errors.go, Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify.go, Godeps/_workspace/src/github.com/endophage/gotuf/signed/verify_test.go, Godeps/_workspace/src/github.com/endophage/gotuf/tuf.go, client/client.go
=> add ErrExpired to notary client to translate from gotuf ErrExpired

Godeps/Godeps.json, Godeps/_workspace/src/github.com/endophage/gotuf/client/client.go
=> updating gotuf

client/client_root_validation_test.go, keystoremanager/keystoremanager.go, keystoremanager/keystoremanager_test.go
Adding tests for certs to remove and moving tests to the right file.
=> Adding tests for CertsToRemove, and move tests around

server/handlers/default.go
=> Removing Writing data debug line

cmd/notary/tuf.go
@diogomonica @NathanMcCauley @endophage
Fixes #111
=> Only skip TLS certificate verification if this is explicitly specified in the config

trustmanager/keyfilestore.go, trustmanager/keyfilestore_test.go
=> Adding typed error for missing keys

pkg/passphrase/passphrase.go
Updates the prompt receiver to take in the in and out files from arguments.
The default function uses stdin and stdout.
Fixed a typo in comment from "directiory" to "directory".
=> Add passphrase function with file input

client/client.go
=> change error log to debug

cmd/notary-signer/config.json, cmd/notary-signer/main.go, docker-compose.yml, notary-signer-Dockerfile, server/handlers/default.go, trustmanager/keydbstore_test.go
=> Adding support for passphrases from env

Makefile
@diogomonica you can only have nice things if you review a PR on docker/docker
=> add back html

cmd/notary/keys.go, cmd/notary/main.go, cmd/notary/tuf.go
Started the work to support a better cli.
- Removed local truststores
- Added configurable base directory
- Added configurable remote server
- Fixed key listing/removal
=> Removed all local keystores, added configurable trust dir

docs/Dockerfile, docs/Makefile, docs/README.md, docs/index.md, docs/overview.md, docs/pre-process.sh
- Created an index.md file that serves to create a menu
- Created overview.md
- README for how to interact
=> Docs infrastructure

cmd/notary-server/config.json, cmd/notary-server/dev-config.json, cmd/notary-server/main.go
=> parse string log level from config

notarymysql/initial.sql
=> update initial.sql to make schema consistent with staging/prod

cmd/notary-server/config.json
=> don't want bugsnag config template in config.json

cmd/notary-server/main.go, server/server.go
=> hard fail if TLS is only partially configured

pkg/passphrase/passphrase.go
@dmcgowan @aaronlehmann 
Signed-off-by: Nathan McCauley <nathan.mccauley@docker.com>
=> Safer, cleaner use of aliasMap

Makefile
not everyone has godeps and all that crap on their host, namely me, i do not so
yeah.... this is better
=> Updates to Makefile

cmd/notary-server/main.go, cmd/notary-signer/main.go
=> add version to signer and server logs for debugging and issues

utils/http.go
If Authorized returns an error, it returns nil for ctx. This means the
deferred function will dereference a nil pointer.
=> Don't blindly overwrite ctx with result of Authorized

Godeps/Godeps.json, Godeps/_workspace/src/github.com/mitchellh/go-homedir/LICENSE, Godeps/_workspace/src/github.com/mitchellh/go-homedir/README.md, Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir.go, Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir_test.go, cmd/notary/main.go
Fixes #194.  Static builds couldn't find homedir on darwin.
=> Make static cross darwin builds work

cmd/notary/main.go, docs/cli.md, docs/index.md
- Add the `--server` parameter for `verify``
- Add and environment variable to specify the default server URL
=> Minor improvements on server url

README.md, cmd/notary-server/dev-config.json
I'm not sure if this is helpful - these things were non-obvious to me, but I am new to Go as well as new to notary.
Parts of this may get too specific (wrt Mac OS and Homebrew) for the README.  Happy to move this stuff elsewhere, or just close if it's too obvious :)
Signed-off-by: Ying Li ying.li@docker.com
=> More details in the README on how to compile notary and run the README example

Makefile
Signed-off-by: Viktor Stanchev <me@viktorstanchev.com>
=> add `make install`, fix #202

Makefile
Removing warnings on make
@NathanMcCauley
=> Fixing makefile warnings

README.md
This makes it easier for new people to see that we are using circle ci and it shows that our tests pass on master.
=> add circle ci badge

Makefile
This reverts commit 77a16d311603533201cc5b147cadbc034abef793.
=> Revert "add `make install`, fix #202"

Godeps/Godeps.json, Godeps/_workspace/src/github.com/endophage/gotuf/client/client.go, Godeps/_workspace/src/github.com/endophage/gotuf/client/errors.go, Godeps/_workspace/src/github.com/endophage/gotuf/store/httpstore.go
=> updating gotuf in godeps

cmd/notary-server/config.json, cmd/notary-server/main.go, cmd/notary-server/main_test.go, cmd/notary-signer/config.json, cmd/notary-signer/main.go, cmd/notary-signer/main_test.go, server/server.go, server/server_test.go, signer/signer_trust.go, trustmanager/keyfilestore_test.go
This is the follow-up PR to #229
=> Support mutual authentication between the server and signer

Dockerfile, Dockerfile.server, Dockerfile.signer, Makefile, docker-compose.yml
=> better named dockerfiles and upgrade to go 1.5.1

README.md
=> Fix broken list

server/server.go, server/server_test.go
=> Add prometheus stats to server http handlers

client/client.go, cryptoservice/crypto_service.go, signer/api/rsa_hardware_crypto_service.go, signer/signer_trust.go, tuf/signed/ed25519.go, tuf/signed/interface.go, tuf/signed/sign_test.go
=> cryptoservices can abstract multiple keystores

keystoremanager/import_export_test.go
=> Remove a left-over debugging Println

tuf/client/client.go
=> Don't compute an unnecessary cryptographic hash

notarymysql/start
It may inconsistent on different hosts(8/4 spaces per tab).
This change remove 2 tabs and add 8 spaces.
=> Replace tab with space on script

trustmanager/yubikey/yubikeystore.go
This unfortunately prints out every time any operation is done on the Yubikey, producing a lot of log output, but perhaps that is better because an operation might fail at any given time.
Output if no Yubikey:
`DEBU[0000] Failed to initialize PKCS11 environment: loaded library /usr/local/lib/libykcs11.dylib, but no HSM slots found 
`
If there is a Yubikey:
`DEBU[0000] Initialized PKCS11 library /usr/local/lib/libykcs11.dylib and started HSM session`
Fixes #281.
=> Log whether a pkcs11 library was found and if it was loadable.

cmd/notary/tuf.go
Uses the same tablewriter we're using for keys.
=> pretty printing targets

cmd/notary/main.go
=> Set the default output for all cobra commands to be STDOUT

docs/Dockerfile, docs/README.md
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
=> Docs fixes for docs validation

cmd/notary-server/config.json, cmd/notary-signer/config.json, notarymysql/start
This way no password is needed.
As per https://github.com/docker/notary/pull/304#discussion_r45666968.
=> Just connect to mysql as root, rather than as dockerdemo user.

cryptoservice/crypto_service.go, cryptoservice/crypto_service_test.go, signer/api/api.go, signer/api/rpc_api.go, signer/client/signer_trust.go, tuf/signed/ed25519.go, tuf/signed/interface.go
=> CryptoService.Sign is now dead code. Remove it and update tests

notarymysql/start
Signed-off-by: Matt Bentley <matt@docker.com>
=> Added check to skip db import if exists

server/handlers/default.go, server/handlers/default_test.go, server/handlers/errors.go, server/handlers/validation.go, server/handlers/validation_test.go, server/snapshot/snapshot.go, server/snapshot/snapshot_test.go, server/storage/interface.go, server/timestamp/timestamp.go, server/timestamp/timestamp_test.go
This builds on top of #329 to add optional server side snapshotting.
=> Server snapshot

server/handlers/default.go, server/handlers/default_test.go, server/server.go, server/server_test.go, tuf/signed/ed25519.go, tuf/signed/ed25519_test.go
This adds a handler for getting the snapshot key.
Based on #332
=> Get Snapshot Key Handler

signer/api/api.go
=> fixing incomplete comment as raised in #340

client/client.go, client/repo.go, client/repo_pkcs11.go
=> Minor refactor of NotaryRepository constructor to use more shared code.

signer/api/api.go, signer/api/api_test.go, signer/client/signer_trust.go
As the language spec:
https://golang.org/ref/spec#Index_expressions
And also fix a typo.
=> Use canonical way to check if a map contains a key

server/handlers/default.go
=> Refactor a little to reduce indentation

Makefile, server/handlers/validation.go, server/handlers/validation_test.go, server/snapshot/snapshot.go, server/snapshot/snapshot_test.go
cc @mtrmac (not sure if the title inclusion will ping)
c.f. https://github.com/docker/notary/pull/332
=> fixing bugs raised by @mtrmac

README.md, docs/notary-server-config.md, docs/notary-signer.md
Fixes a 404 link in the readme, and some small typos in the docs
=> readme and doc typo fixes

docs/notary-server-config.md, docs/notary-signer-config.md
Greate docs but still have some nit.
=> Docs: update docs for notary config

server/handlers/default.go, server/handlers/validation.go, server/handlers/validation_test.go, server/storage/database.go, server/storage/database_test.go, server/storage/memory.go, server/storage/memory_test.go, server/timestamp/timestamp.go, tuf/tuf.go, tuf/tuf_test.go, tuf/utils/role_sort.go, tuf/utils/role_sort_test.go
=> server side delegations support in validation and snapshot generation

tuf/store/filestore.go, tuf/store/filestore_test.go
=> Ensure that SetMeta creates parent directory first

client/client.go, client/client_root_validation_test.go, client/client_test.go, client/helpers.go, cmd/notary/tuf.go, server/server.go, tuf/client/client.go, tuf/client/client_test.go, tuf/data/roles.go, tuf/data/targets.go, tuf/tuf.go, tuf/utils/stack.go, tuf/utils/stack_test.go
=> download all delegated roles when doing downloadTargets

client/client_test.go, client/helpers_test.go
Should address some of the tests in https://github.com/docker/notary/issues/363
Semantic conflict with #384
=> Add more delegation writing/publishing tests.

client/client.go, client/client_test.go, cmd/notary/integration_test.go, cryptoservice/import_export.go, cryptoservice/import_export_test.go, server/server_test.go, trustmanager/filestore.go, trustmanager/filestore_test.go, trustmanager/keyfilestore.go, trustmanager/keyfilestore_test.go, trustmanager/memorystore.go, trustmanager/store.go, trustmanager/x509utils.go, trustmanager/x509utils_test.go, trustmanager/yubikey/yubikeystore_test.go, tuf/tuf.go
This is just #383 rebased and with review comments addressed.
This also passes with #387
=> Rebased cleanup/remove PEM headers

signer/api/api.go
GetCryptoService is a helper function and we have injected a specific
http.ResponseWriter object for it to write back error message. Meanwhile
the caller for that function checks whether the cryptoService is nil
or not and return immediately if it is nil.
I think it's not a good idea to write back HTTP response in the helper function,
it's the caller's work and thus there is no need to inject the specific
ResponseWriter object into it.
=> Stop injecting to the helper function

tuf/data/roles.go, tuf/store/httpstore.go, tuf/tuf.go, tuf/validation/errors.go
Style cleanup from @aaronlehmann's helpful comments!
=> fix up style according to comments

docs/opensslCertGen.sh
It seems the prompt doesn't work here.
=> Fix here document

misc/dockertest.py
Used this to test https://github.com/docker/docker/pull/18887.
=> Add a miscellaneous script for testing docker trust functions with notary

MAINTAINERS
=> Add to maintainers list

docs/index.md
=> Fix broken links

migrations/server/mysql/0003_add_sha256_tuf_files.down.sql, migrations/server/mysql/0003_add_sha256_tuf_files.up.sql, notarymysql/initial.sql, server/storage/database.go, server/storage/database_test.go, server/storage/models.go
=> adding sha256 column to tuf_files database table

tuf/client/client.go
=> Improve client logging

client/client_test.go, cmd/notary/prettyprint.go, cmd/notary/prettyprint_test.go, trustmanager/keyfilestore_test.go
Adds test to make sure we can just put keys in tuf_keys successfully (for user keys)
=> Test dropping keys in tuf_keys

tuf/client/client.go
=> Fix a wrong function call

certs/certs.go
=> Comments: minor typo

client/client.go, client/client_test.go
=> Do not lowercase role names when adding a change

client/client.go
Just to keep consistent with the others.
=> Tiny refactor

cmd/notary/delegations.go, cmd/notary/delegations_test.go, cmd/notary/integration_test.go, cmd/notary/prettyprint.go, cmd/notary/prettyprint_test.go
Would love any suggestions for better messages on the CLI.  Closes #487, #488, #490.
=> delegations CLI UX improvements

docs/upgrading-client.md
So that we have something to link against from docker.
=> Add a doc about how to upgrade to v0.2.

cmd/notary/integration_test.go, cmd/notary/keys.go, cmd/notary/keys_test.go
Introduces a `notary key passwd` command that takes a root key ID and allows the user to change its encryption passphrase.
Partially addresses https://github.com/docker/notary/issues/424 since this only considers root keys, but allowing passphrase changes on individual targets or snapshot keys would require changes to the passphrase retriever since we bundle the keys together for usability (we don't expose how there are two separate keys with the same targets passphrase to the user on repo creation)
```
$ notary key passwd b96f10739347d960ef964ec946b9c3b26d443d57b09cfa574f4ab93a8614f954
Enter passphrase for root key with ID b96f107:
You are about to create a new root signing key passphrase. This passphrase
will be used to protect the most sensitive key in your signing system. Please …
```
=> passwd command and tests

docs/notary-server.md
=> adding doc for notary-server -logf option

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/go-connections/tlsconfig/config.go, Godeps/_workspace/src/github.com/docker/go-connections/tlsconfig/config_client_ciphers.go, Godeps/_workspace/src/github.com/docker/go-connections/tlsconfig/config_legacy_client_ciphers.go
This is just the vendor of the package.  Part of #452
=> Add the github.com/docker/go-connections/tlsconfig dependency to godeps

cmd/notary/cert.go, cmd/notary/delegations.go, cmd/notary/delegations_test.go, cmd/notary/integration_nonpkcs11_test.go, cmd/notary/integration_pkcs11_test.go, cmd/notary/integration_test.go, cmd/notary/keys.go, cmd/notary/keys_test.go, cmd/notary/main.go, cmd/notary/main_test.go, cmd/notary/tuf.go, cmd/notary/tuf_test.go
… and to not exit on error.
I couldn't quite debug the flags persisting between tests while I was working on #452 - this should make it easier to test. (and seems to fix my problems for that issue)
To that end, I added a couple tests.
=> Refactor the notary command line to not use global mutable state

docs/index.md
ping @docker/notary-maintainers
=> Change Notary to show Docker Notary in menu

Makefile
Just creates static builds of server and signer for reliable use with alpine container for official images.
I'm by no means good at Makefiles so let me know if there's a better way to do this. 
=> adding additional 'make static' command 

docs/Dockerfile
- remove tutorials, that repo is now private
- add notary as that component is now building
- add toolbox as that component is now building
- change ownership of kitematic to docker as that repo moved
- added missing swarm
=> Updating Dockefile

docs/notary-server-config.md
=> Minor typo

client/client.go, client/client_test.go, tuf/client/client.go, tuf/client/client_test.go, tuf/data/roles.go, tuf/tuf.go, tuf/tuf_test.go
=> Delegation path and rolename fixes

misc/dockertest.py
Based on some feedback from @endophage testing it out earlier.
In particular, allow setting the username by environment variable, and use a temporary docker config directory.
=> Update dockertest file

Godeps/Godeps.json, Godeps/_workspace/src/github.com/miekg/pkcs11/README.md, Godeps/_workspace/src/github.com/miekg/pkcs11/const.go, Godeps/_workspace/src/github.com/miekg/pkcs11/parallel_test.go, Godeps/_workspace/src/github.com/miekg/pkcs11/pkcs11.go, Godeps/_workspace/src/github.com/miekg/pkcs11/pkcs11_test.go, Godeps/_workspace/src/github.com/miekg/pkcs11/types.go
@diogomonica @riyazdf @cyli Please LGTM ASAP. Jenkins tests are breaking when we upgrade go the 1.6 over there.
=> updating miekg/pkcs11 for go 1.6

tuf/data/snapshot.go
=> Cleanup: remove the unused function

tuf/utils/utils.go
=> Kind of cleanup

CHANGELOG.md
I've started a `CHANGELOG.md` file to track release notes.  I'm not as familiar with notary versioning prior to 0.2 (and I might have missed notes for 0.2 as well), so please feel free to jump in and add whatever notes are appropriate.
=> notary 0.2 changelog

cmd/notary-server/main_test.go, cmd/notary-signer/main.go, server/storage/database.go
=> Move all imports of sqlite3 to tests only

server/handlers/validation.go
=> Fix mispelling of 'occur'

utils/configuration_test.go, utils/http_test.go
Part of  #628 
Replace the use of the "assert" package with the "require" package.
=> Package replace

docs/reference/server-config.md
=> Docs: typo

client/client_test.go, server/timestamp/timestamp.go, tuf/data/root.go, tuf/data/root_test.go, tuf/data/snapshot.go, tuf/data/snapshot_test.go, tuf/data/targets.go, tuf/data/targets_test.go, tuf/data/timestamp.go, tuf/data/timestamp_test.go, tuf/data/types.go, tuf/signed/sign.go, tuf/signed/sign_test.go, tuf/signed/verify.go, tuf/signed/verify_test.go, tuf/store/httpstore_test.go, tuf/testutils/swizzler.go, tuf/testutils/swizzler_test.go
=> update top level Signed.Signed to be a *json.RawMessage

cmd/notary/main.go, docs/reference/client-config.md
Adds an environment variable for notary to try against delegation role passphrases, for automation and testing purposes.
=> Delegation password environment var

docs/advanced_usage.md
Documents the docker push/pull behavior for Docker 1.10 & 1.11
=> Update notary docs to reflect DCT delegations behavior

client/client.go, server/snapshot/snapshot.go, tuf/client/client.go, tuf/data/snapshot.go, tuf/tuf.go
=> Use constant

tuf/data/errors.go, tuf/data/types.go, tuf/data/types_test.go
Use concrete error types.
Fixes #619
=> Error types

server/handlers/default_test.go, server/handlers/validation_test.go, server/integration_test.go, server/server_test.go, server/snapshot/snapshot_test.go, server/storage/memory_test.go, server/timestamp/timestamp_test.go
=> Change github.com/docker/notary/server/... tests to use require

buildscripts/integrationtest.sh, development.yml, docker-compose.yml, migrations/migrate.sh, server.Dockerfile, signer.Dockerfile
Fixes #635.
Thanks to @ncopa for his solution at https://github.com/golang/go/issues/14851.
=> Convert the server and signer images to use alpine

tuf/encrypted/encrypted_test.go, tuf/signed/verifiers_test.go, tuf/store/filestore_test.go, tuf/store/httpstore_test.go, tuf/testutils/swizzler_test.go, tuf/tuf_test.go, tuf/utils/role_sort_test.go, tuf/utils/stack_test.go, tuf/utils/util_test.go, tuf/utils/utils_test.go
=> Finish converting assert to require in tuf/* packages

client/changelist/change_test.go, client/changelist/changelist_test.go, client/changelist/file_changelist_test.go
This should be the last part of #628
=> Change assert to require in client/changelist

docs/service_architecture.md
"These files" and "They" are plural.
=> Minor grammar fix in TUF overview

Makefile, cmd/notary-signer/main.go, cmd/notary-signer/main_test.go
Also, remove `+build pkcs11 ` build tag from the signer.
Thanks to @endophage for noticing that previously, signer tests weren't be run  :(
=> Add the buildtags to go list ./... in the Makefile

README.md, client/client.go, client/repo.go, cmd/notary-signer/main.go, cmd/notary/main.go, docs/advanced_usage.md, docs/reference/client-config.md, docs/reference/common-configs.md, docs/service_architecture.md
Monday morning is a good time to read docs :)
Fixed some broken links , typo, etc.
=> Docs: some review

client/client.go, client/client_update_test.go, tuf/store/filestore.go, tuf/store/filestore_test.go, tuf/store/httpstore.go, tuf/store/httpstore_test.go, tuf/store/interfaces.go, tuf/store/memorystore.go, tuf/store/memorystore_test.go, tuf/testutils/swizzler.go, tuf/testutils/swizzler_test.go
=> Add const for max size -1 for GetMeta

codecov.yml
=> Add a codecov config file that disables project and changes statuses

cmd/notary/tuf.go, cmd/notary/util.go, cmd/notary/util_test.go
There is no reason to give out all the payload especially when it is
huge engough, it will definitely ruin the console.
=> Feature: Introduce some flags on notary verify

CHANGELOG.md
=> update changelog for v0.3.0

docs/changelog.md
Highlights the major features in 0.3 for docs.docker.com
Mentioned in #741
=> Add short changelog update to docs

client/client_test.go, cmd/notary-server/config.go, cmd/notary-server/main_test.go, cmd/notary/integration_test.go, cmd/notary/keys_test.go, docs/reference/server-config.md, server/errors/errors.go, server/integration_test.go, server/server.go, server/server_test.go, utils/http.go
=> Server gun prefix requirement feature

server/storage/rethinkdb.go, server/storage/rethinkdb_models.go, signer/keydbstore/rethink_keydbstore.go
To make retrieving table information for rethinkdb easier for integrations.
=> Export rethinkdb table definitions

client/changelist/change.go, client/client.go, client/client_test.go, client/helpers.go, server/integration_test.go, server/storage/rethinkdb.go, server/storage/rethinkdb_models.go, server/storage/tuf_store_test.go, trustmanager/keyfilestore.go, trustpinning/certs_test.go, tuf/README.md, tuf/testutils/repo.go
Made Tuf and tuf- TUF in all comments, rethink models and readmes according to issue #313 
Signed-off-by: avaid96 <avaid1996@gmail.com>
=> TUF changed to Tuf

server/storage/rethinkdb.go, server/storage/rethinkdb_models.go, server/storage/rethinkdb_test.go, signer/keydbstore/rethink_keydbstore.go, signer/keydbstore/rethink_keydbstore_test.go, storage/rethinkdb/bootstrap.go
This is a replacement for #770.
=> Add JSON marshalling and unmarshalling specific model types to rethink Table object

server/handlers/default.go
Adds error-level logging for 500 status codes during an update call to notary server, which can be caught by bugsnag.
=> Error logging for POSTs to notary server

development.rethink.yml, docker-compose.rethink.yml
See https://hub.docker.com/r/jlhawn/rethinkdb/tags/2.3.0/
=> Bump rethink version due to vulnerabilites in 2.3.0 image

tuf/README.md
=> Edited tuf/README

Dockerfile, server.Dockerfile, signer.Dockerfile
=> Bump the golang-alpine image version due to CVEs

README.md
Go Report Card assesses the project on code-quality metrics like vet, lint, fmt, misspell, and more!
=> Add goreportcard badge

client/client_test.go, passphrase/passphrase.go, server/handlers/validation_test.go, server/storage/database_test.go, signer/api/api_test.go, trustmanager/x509utils_test.go, trustmanager/yubikey/yubikeystore.go
Low hanging fruit. The cyclo changes will take a little more attention so we can do them separately
=> addressing vet and ineffassign items in goreport

server/storage/rethinkdb.go
Adds a simple healthcheck for the `notaryserver` RethinkDB, checking that it is queryable and its tables exist.
Closes #849.
=> Server rethinkdb healthcheck

client/client.go, cmd/notary/tuf.go, tuf/data/targets.go, tuf/tuf.go
=> Misc: some code review

Makefile, cryptoservice/crypto_service_test.go, trustmanager/yubikey/yubikeystore_test.go, tuf/tuf.go, tuf/tuf_test.go
Cherrypicks @jchorl's commit that fixes misspell from his notifications PR
=> Fix misspell with update

docs/service_architecture.md, trustmanager/yubikey/yubikeystore.go
Short PR to fix a typo reported in an issue.  Also found another similar typo as a bonus
Closes #833
=> fix access typos, close 833

buildscripts/testclient.py
Noticed that the format index needed a slight tweak when I hit a timeout
=> small fixup to test client

trustmanager/keystore.go
closes #310 
Signed-off-by: Avi Vaid <avaid1996@gmail.com>
=> made fix as per open issue 310

cmd/notary/delegations.go, cmd/notary/integration_test.go
Add the auto-publish flag for `notary delegation purge` 
=> add auto-publish to purge

client/client.go, client/client_test.go
"" will retrieve all targets signed into the repository, across all roles.
=> Allow empty string for GetAllTargetMetadataByName

cmd/notary/tuf.go
=> Fix gocyclo warning

docs/advanced_usage.md, docs/getting_started.md
=> docs for status --unstage/reset and witness

buildscripts/testclient.py
=> Bump up wait time for integration tests, and fix formatting error

docs/best_practices.md, docs/index.md
Closes #406 
Totally retroactively justifies our 10 year cert expiry on root keys :-P
=> best practices doc

client/changelist/change.go, client/client.go, client/helpers.go
=> Fix confusing naming

buildscripts/covertest.py
Run go test on packages that don't have test files, but don't get cross-package coverage for them.
Since the cross-package coverage probably slows them down.
But as per https://github.com/golang/go/issues/17248, running `go test` on those packages makes sure they will actually build (no compile errors).  So try to run them without the `-race` and `coverpkg` options.  I think we have basically almost everything covered given cross-package coverage for other packages and integration tests, but always good to ensure we actually cover everything.  :)
This brings CI time up to 16 minutes or so from 15.
=> Slow CI back down a bit

client/client_test.go, cmd/notary-server/bootstrap.go, cmd/notary-server/bootstrap_test.go, cmd/notary-server/config.go, cmd/notary/integration_test.go, cmd/notary/keys_test.go, notary.go, server/handlers/default.go, server/handlers/default_test.go, server/handlers/roles.go, server/handlers/roles_test.go, server/integration_test.go, server/server_test.go, utils/http.go
https://github.com/golang/lint/pull/245
https://github.com/golang/go/issues/17293
=> lint was updated per linked issues. This fixes new requirement

client/changelist/change.go, cmd/notary-signer/main_test.go, cmd/notary/tuf_test.go, passphrase/passphrase.go, signer/rpc_and_client_test.go, storage/filestore.go, storage/rethinkdb/rethinkdb.go, tuf/data/types.go, tuf/signed/verifiers.go, tuf/signed/verify.go, tuf/testutils/repo.go, tuf/utils/utils.go, tuf/utils/x509.go
My IDE helped me find a bunch of unused functions and variables (and redundant import aliases), which includes a couple of unused lines that are being alerted by https://gas.css.bio/#docker/notary
=> Remove unused functions and aliases

const.go, server/handlers/changefeed.go, server/handlers/changefeed_test.go
=> set max page size for changefeed

cmd/notary/main.go, cmd/notary/migrations.go, cmd/notary/migrations_test.go
=> Delete trusted certs

cmd/notary/integration_test.go, cmd/notary/keys.go, cmd/notary/keys_test.go, cmd/notary/main_test.go, cmd/notary/tuf.go, const.go, server/handlers/roles.go, server/storage/rethinkdb.go, server/storage/rethinkdb_models.go, server/storage/rethinkdb_test.go, server/storage/sql_models.go, server/storage/sqldb.go, server/storage/sqldb_test.go, server/storage/storage_test.go, server/storage/tuf_store.go, server/storage/tuf_store_test.go, server/timestamp/timestamp.go, trustmanager/keystore_test.go, tuf/data/types_test.go, tuf/utils/utils.go
=> fixing Sha256 capitalization per Go rules on acronyms

docs/reference/server-config.md, docs/reference/signer-config.md
Signed-off-by: Misty Stanley-Jones <misty@docker.com>
=> Fix some doubled words in references

server/handlers/changefeed.go
It's a good choice to use the constants we already have.
=> Some code review

fixtures/server-config-local.json, fixtures/server-config.json, fixtures/server-config.postgres.json, fixtures/server-config.rethink.json
Changed spaces to tabs in config files specified in Issue #1013
=> fix formatting in fixture config json files

MAINTAINERS
=> Add ecordell as a maintainer

cmd/notary/tuf.go, vendor.conf, vendor/github.com/docker/distribution/blobs.go, vendor/github.com/docker/distribution/context/http.go, vendor/github.com/docker/distribution/manifests.go, vendor/github.com/docker/distribution/reference/reference.go, vendor/github.com/docker/distribution/registry/api/errcode/register.go, vendor/github.com/docker/distribution/registry/api/v2/descriptors.go, vendor/github.com/docker/distribution/registry/api/v2/headerparser.go, vendor/github.com/docker/distribution/registry/api/v2/urls.go, vendor/github.com/docker/distribution/registry/auth/auth.go, vendor/github.com/docker/distribution/registry/auth/htpasswd/access.go, vendor/github.com/docker/distribution/registry/auth/token/accesscontroller.go, vendor/github.com/docker/distribution/registry/auth/token/token.go, vendor/github.com/docker/distribution/registry/client/auth/challenge/addr.go, vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go, vendor/github.com/docker/distribution/registry/client/auth/session.go, vendor/github.com/docker/distribution/registry/client/errors.go, vendor/github.com/docker/distribution/registry/client/repository.go, vendor/github.com/docker/distribution/registry/client/transport/http_reader.go, vendor/github.com/docker/distribution/registry/storage/cache/memory/memory.go
Also replaces `auth.NewSimpleChallengeManager` with  `challenge.NewSimpleManager`
Closes https://github.com/docker/notary/issues/999
=> Bump distribution to 2.6.0

utils/http.go
A quick fix for the "nil reference" error, more details in #1097 
Signed-off-by: Tan Jiang <jiangd@vmware.com>
=> fixes #1097

server.Dockerfile, signer.Dockerfile
temporary workaround for https://github.com/mattes/migrate/issues/202 since we have not tested v3 nor does it support all drivers yet
Closes https://github.com/docker/notary/issues/1142
=> Pin migrate binary

Dockerfile, cross.Dockerfile, server.Dockerfile, signer.Dockerfile
Updates to golang 1.8.3.  Of note, [1.8.2](https://groups.google.com/forum/#!topic/golang-nuts/vbHB2zj5xCk) included a security fix, and [1.8.3](https://groups.google.com/forum/#!topic/golang-nuts/oUOV9PFq_8s) has functionality fixes.
Signed-off-by: Riyaz Faizullabhoy <riyazdf@berkeley.edu>
=> update to golang 1.8.3

docs/reference/client-config.md
Signed-off-by: JimGalasyn <jim.galasyn@docker.com>
Fixes [typo](https://github.com/docker/docker.github.io/issues/3246).
=> Update tls_client_key example path

docs/reference/client-config.md
I removed the center tags to show the validation flow correctly, also I added the complete url.
=> Fix broken image because center tags

LICENSE
This is just bookkeeping/cleanup.
=> at some point we chopped the first line off the license

tuf/utils/x509.go
=> Change gun to commonName in NewCertificate function

vendor.conf
Changed vendor.conf to add git hashes. 
=> add git hashes

client/client.go, trustpinning/trustpin.go, tuf/data/types.go
This makes the client package a little more approachable and give sa
basic example of how to get started.
ping @riyazdf
=> Add more details to a few doc strings

README.md, docs/images/notary-blk.svg, docs/images/notary-n-blk.svg, docs/images/notary-n-wht.svg, docs/images/notary-wth.svg
The docker design team requested that they do the Logo before the project lands in CNCF. This PR should be considered the vote. I will be responsible for merging assuming this passes  the two-thirds vote.
+1 from me.
=> adding logo

README.md
=> add a notice about moving the repo to the start of the README

cmd/notary-signer/main.go
=> Fix the message for debug mode in signer

vendor.conf, vendor/github.com/dvsekhvalnov/jose2go/README.md, vendor/github.com/dvsekhvalnov/jose2go/ecdh.go, vendor/github.com/dvsekhvalnov/jose2go/jose.go
release notes say:
v1.3 fixed potential Invalid Curve Attack on NIST curves within ECDH key management.
Upgrade strongly recommended.
=> Update dvsekhvalnov/jose2go to 1.3

vendor.conf, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/NOTICE, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go
This includes the relicensing from LGPLv3 to Apache, and
numerous updates.
fix #1321 
=> Update yaml library

CODE_OF_CONDUCT.md
This is the Github recommended filename.
=> Add the CNCF Code of Conduct

Makefile
The repo has moved and instructions changed.
=> Update instructions for getting gas

Dockerfile, cross.Dockerfile, escrow.Dockerfile, server.Dockerfile, server.minimal.Dockerfile, signer.Dockerfile, signer.minimal.Dockerfile
Not a security update as far as I can see, but small fixes.
=> Update to Go 1.10.2

MAINTAINERS
Thanks for inviting me ;)
TUF work...
=> Add Justin Cormack to Maintainers

client/changelist/interface.go, client/interface.go, cmd/notary/prettyprint.go, server/storage/sqldb_test.go, storage/rethinkdb/bootstrap.go, tuf/data/snapshot.go, tuf/data/targets.go, tuf/signed/interface.go, utils/configuration.go
This PR fixes many typos in various places.
=> Fix many typos

buildscripts/covertest.py, client/client_test.go, server/storage/rethinkdb.go, server/storage/sql_models.go
Although it is spelling mistakes, it might make an affects
while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Remove duplicated words in comments

cmd/notary/keys.go
=> Fix algorithm case handling (fix #1471)

tuf/data/types.go, tuf/data/types_test.go
Signed-off-by: Max Schaefer <max@semmle.com>
=> Fix `FileMeta.Equals`.

Dockerfile, Makefile, cmd/notary/integration_test.go
=> Update Go to 1.12.7

cmd/notary/keys.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: help message words correction in keys.go

docs/advanced_usage.md
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
Correct spelling mistakes.
=> Correct spelling mistakes

utils/auth_test.go, utils/http.go, utils/http_test.go, vendor.conf, vendor/github.com/docker/distribution/blobs.go, vendor/github.com/docker/distribution/context/http.go, vendor/github.com/docker/distribution/errors.go, vendor/github.com/docker/distribution/health/health.go, vendor/github.com/docker/distribution/registry.go, vendor/github.com/docker/distribution/registry/api/v2/routes.go, vendor/github.com/docker/distribution/registry/auth/auth.go, vendor/github.com/docker/distribution/registry/auth/htpasswd/access.go, vendor/github.com/docker/distribution/registry/auth/htpasswd/htpasswd.go, vendor/github.com/docker/distribution/registry/auth/silly/access.go, vendor/github.com/docker/distribution/registry/auth/token/accesscontroller.go, vendor/github.com/docker/distribution/registry/client/auth/session.go, vendor/github.com/docker/distribution/registry/client/repository.go, vendor/github.com/docker/distribution/registry/client/transport/http_reader.go, vendor/github.com/docker/distribution/vendor.conf, vendor/github.com/opencontainers/image-spec/LICENSE, vendor/github.com/opencontainers/image-spec/README.md, vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go, vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
=> Update docker/distribution to 2.7.1

tuf/utils/utils_test.go
This PR is about adding some unit tests for tuf/utils/utils.go.
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Add some unit tests for tuf/utils/utils.go

CHANGELOG.md
This is primarily a release to switch to go mod modules in a release
version.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
=> Add Changelog for v0.7.0 release

CODEOWNERS, MAINTAINERS
Addressing https://github.com/notaryproject/.github/issues/55 https://github.com/notaryproject/.github/issues/56 and https://github.com/notaryproject/.github/issues/57
=> Updated MAINTAINERS added CODEOWNERS files
